### ISSUE TITLE
Some aria-labels assume the current language is English

### ISSUE THREAD

**Issue by efischer19** [openedx/paragon#139]
For example, [the `"Close"` string seen here](https://github.com/edx/paragon/blob/b783247b0133fc5c64d2d58561c08541cb3bf0b3/src/StatusAlert/index.jsx#L71)

Ideally, these should be i18n-able yes?

I'm not super sure how we'll be able to make this work, but I noticed it during my current work and wanted to make sure I made a note somewhere.

**Comment by jaebradley** [comment]
@efischer19 ahhh good point - we should probably create a prop for `aria-label`s with an English default prop value?

That seems like the most obvious solution but maybe there's a better way?

**Comment by efischer19** [comment]
Can aria-labels have props? I was under the impression that they could only be strings.

The super-far-fetched ideal is to get paragon working with `react-intl`, but that will require extracting/translating all display strings contained within, similar to the work I've got in progress at https://github.com/edx/studio-frontend/pull/84.

**Comment by jaebradley** [comment]
@efischer19 

I think you could do something like

![image](https://user-images.githubusercontent.com/8136030/35689161-db3d71a8-0740-11e8-9d4e-98ea76db8851.png)

```javascript
import React from 'react';
import PropTypes from 'prop-types';

const Example = ({ ariaLabel }) => (
  <div aria-label={ ariaLabel }>{ `This is an example with aria-label: ${ariaLabel}`}</div>
);

Example.defaultProps = {
  ariaLabel: 'foobar',
};

Example.propTypes = {
  ariaLabel: PropTypes.string,
};

export default Example;
```

Could totally be misunderstanding though. 

Basically, I am not sure if we should handle `i18n` compatibility in Paragon - instead, we should allow the API user to determine what values to use.

[StackBlitz example](https://stackblitz.com/edit/aria-label-prop-example)

**Comment by efischer19** [comment]
Oh I see what you're saying - we could definitely make the aria-labels be props [like we do here in Modal](https://github.com/edx/paragon/blob/f702b7b5d47ddec3c2845d1b4cc1b07eff031d4c/src/Modal/index.jsx#L177), I was saying there's no way to give the aria-label its own prop (for example, a `lang` prop identifying what language is currently being used)

I'm fine leaving it as an open question for now.

**Comment by adamstankiewicz** [comment]
We are moving towards adding i18n support natively in Paragon, hosting its own translated messages so consumers no longer have to provide translations if using the default English messages, or where some messages are not currently customizable.
