### ISSUE TITLE
Add semantic card status to docsite

### ISSUE THREAD

**Issue by gabew1984** [openedx/paragon#1473]
Semantic card status has been designed but has not been added to the docsite yet. Not sure if this has been built yet.

https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=14061%3A6

**Comment by viktorrusakov** [comment]
Card status has already been implemented in https://github.com/openedx/paragon/issues/1328, you can see examples on the docs site in the [Card page](https://paragon-openedx.netlify.app/components/card/#card-status).
