### ISSUE TITLE
Design tokens documentation

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#1546]
**AC**
- Write and update documentation about design tokens, style-dictionary, and theming for both engineers and designers in the [Open edX Confluence space](https://openedx.atlassian.net/wiki/spaces/BPL/overview) and [documentation website](https://paragon-openedx.netlify.app/), [Paragon's README](https://github.com/openedx/paragon/blob/master/README.md)
- Create an ADR in Paragon describing decision to move to design tokens

### PRs

- [x] https://github.com/openedx/paragon/pull/1623
- [x] https://github.com/openedx/paragon/pull/1929

**Comment by arbrandes** [comment]
Community project manager check: I see the PR was merged.  Anything else that needs doing?

**Comment by viktorrusakov** [comment]
@arbrandes Yeah, I don't think that PR was enough, that was just an initial documentation that we'll need to improve on (probably in follow-up issues). As for this issue - I'd like us to create a proper ADR related to design tokens first, we will close this issue once it gets merged, hopefully this or next week 🙂

**Comment by arbrandes** [comment]
@viktorrusakov, sprint check: got any updates for us?  Thanks!

**Comment by arbrandes** [comment]
Linking to ADR for future reference:

https://github.com/openedx/paragon/pull/1929

**Comment by viktorrusakov** [comment]
this one is also related: #1905

**Comment by arbrandes** [comment]
I think we can call this done.
