### ISSUE TITLE
Importing core.scss is broken due to missing Bootstrap Variables

### ISSUE THREAD

**Issue by tecoholic** [openedx/paragon#1559]
## Description

I am trying to update the `@edx/paragon` version from 12.x to 20.x in [edx-ora2](https://github.com/openedx/edx-ora2/pull/1869) due to the dependency requirement of React 17.x. However, the build fails with the following error

```
ERROR in ./openassessment/xblock/static/sass/openassessment-rtl.scss (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--5-4!./openassessment/xblock/static/sass/openassessment-rtl.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Undefined variable.
       ╷
    24 │     @include transition($transition-collapse-width);
       │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
       ╵
      node_modules/bootstrap/scss/_transitions.scss 24:25            @import
      node_modules/@edx/paragon/scss/core/core.scss 9:9              @import
      openassessment/xblock/static/sass/_openassessment.scss 99:13   @import
      openassessment/xblock/static/sass/openassessment-rtl.scss 2:9  root stylesheet
```

Once the `node_modules/@edx/paragon/scss/core/core.scss` was edited to include the line

```scss
@import "~bootstrap/scss/variables";
```
above the line ```@import "~bootstrap/scss/transitions";```, the error went away and the build was successful.

So, it seems like that the `core.scss` is missing the required `variables` module from Bootstrap.

## Reproducing the issue

In order to isolate the cause, the following experiment was also conducted.

1. Created a new React Application using the `create-react-app`
2. Downgraded all the dependencies from React 18.x to React 17.x and added `@edx/paragon` and `sass`
    ```
    "dependencies": {
    "@edx/browserslist-config": "^1.1.0",
    "@edx/paragon": "^20.9.1",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/user-event": "^12.1.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4",
    "@testing-library/react": "^12.1.2",
    "sass": "^1.54.4"
    },
    ```
3. Added the `Alert` component from Paragon to App.js and index.scss
    ```jsx
    import "index.scss"
    import {Alert} from "@edx/paragon"
 
    ...
         <Alert variant="success">
            Some alert message
         </Alert>
    ```
4. Imported Paragon SCSS into index.scss.
    ```
    @import "@edx/paragon/scss/core/core.scss";
    ```
5. Adjusted the index.js code to suit React 17.x and started dev server using `npm start`
6. The dev server fails to start due to the same error as reported during the ORA2 upgrade.
7. Edit the `node_modules/@edx/paragon/scss/core/core.scss` file as mentioned above. The dev server builds and the app loads with the Alert component.

### Screenshots

![image](https://user-images.githubusercontent.com/383862/184626357-83b5d6e7-b541-4328-a0f7-b16ccab178a4.png)

#### After adding the variables line

![image](https://user-images.githubusercontent.com/383862/184625688-c9029b2c-e4a1-40d1-b93f-efccf0d333bf.png)

**Comment by pomegranited** [comment]
Thank you for this @tecoholic ! Do you need any help finding an internal and/or external reviewer for this OSPR?

I searched and there's no core committers with merge rights to paragon, but there's 3 people with frontend-app rights: @BbrSofiane @xitij2000 @arbrandes Are any of you interested in expanding your core committer roles to include this repo?

**Comment by tecoholic** [comment]
@pomegranited Looks like the fix is already underway in https://github.com/openedx/paragon/pull/1562. :)

**Comment by pomegranited** [comment]
Even better @tecoholic :)

**Comment by arbrandes** [comment]
@pomegranited 
> Are any of you interested in expanding your core committer roles to include this repo?

This might make sense.  We should ask @adamstankiewicz first, though: are you taking core contributors, Adam? :)
