### ISSUE TITLE
`react-responsive.js` URL is not supported

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1674]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/2828721/194568609-ac9e5038-d567-48a9-8fc7-d3f205c78ecf.png">

The above error appears to occur on every `npm run build` of MFEs. It appears to be related to parsing of a source map, and does not seem to impact the MFE application.

**Comment by solababs** [comment]
@xitij2000 I am unable to reproduce this, can you please help with steps to reproduce this. Thanks.
