### ISSUE TITLE
Implement new docs site design

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#1810]
Design team finished redesigning navigation around documentation site, see [Figma specs](https://www.figma.com/file/KuCj8y3y3D44HfE3dUzuiS/Paragon-docsite-navigation?node-id=347%3A1166&t=ZolQhlClVRQo5F40-0)

**AC**
- implement new design for documentation site from Figma

**Implementation notes**:
- It is not explicitly specified in FIgma, but we should remove categorized components menu from footer, only leave **All components (A-Z)** section there
![image](https://user-images.githubusercontent.com/52399399/204984952-7b2b1dd3-945d-42a0-8963-236285fa8c26.png)

**Comment by viktorrusakov** [comment]
https://github.com/openedx/paragon/pull/1803

**Comment by adamstankiewicz** [comment]
Related issue: https://github.com/openedx/paragon/issues/1583
