### ISSUE TITLE
link variant Button With upload iconBefore not matching link color

### ISSUE THREAD

**Issue by connorhaugh** [openedx/paragon#1816]
Using the `Upload` Icon  as a ` iconBefore` prop to a `Button` Component with the variant `link` does not cast the color of the icon color to blue. You can see it does so with the add icon in the screenshots below. This is also the case with the variant brand and iconafter.

<img width="132" alt="Screen Shot 2022-12-01 at 11 51 53 AM" src="https://user-images.githubusercontent.com/49422820/205112147-5b4131f5-edb7-457c-9fff-fdc1c9bb2305.png">
<img width="145" alt="Screen Shot 2022-12-01 at 11 51 38 AM" src="https://user-images.githubusercontent.com/49422820/205112149-7988046f-2eed-41e9-b05b-3cf8593f1c2d.png">
<img width="142" alt="Screen Shot 2022-12-01 at 11 51 30 AM" src="https://user-images.githubusercontent.com/49422820/205112151-ec7b6570-1e95-45cf-90bc-47a0d7dca9a7.png">
<img width="148" alt="Screen Shot 2022-12-01 at 11 51 20 AM" src="https://user-images.githubusercontent.com/49422820/205112152-c9bb991b-4678-4afa-b949-0f2fcd2dcb51.png">

**Comment by KristinAoki** [comment]
The same issue applies to the `Attribution` icon

**Comment by connorhaugh** [comment]
Ok so @adamstankiewicz I have found the following results as to how we can get this fixed. I did not have time to implement it, however.

Adam pointed out that:
> it looks like the fill="currentColor" is missing on the material-icons SVGs.
> when svgr processes the source SVG files, if fill="none" on the parent svg element and fill="black" on the path elements, it transforms fill="black" to fill="currentColor"; im not entirely sure why that is but its the behavior we want

Here is a summary of the current build process for bring icons from material -> jsx elements:

1. we copy the files into a directory from the package using [copy-mui-icons.js](https://github.com/openedx/paragon/blob/master/icons/copy-mui-icons.js)
2. We then run `npm run-script build` in the icons folder.
3. this runs `node copy-mui-icons.js && svgr svg --out-dir jsx && babel jsx -d es5` presently.
4. This process outputs jsx files which we then use

What we care about here is inserting, between the 3. and 4 a step to add the attribute `fill="none"` to the parent svg and `fill="black"`  on the Path. 
To do this, we can use several bable plugins listed [here](https://react-svgr.com/docs/custom-transformations/) and list the ` babelConfig:` like so:

```
module.exports = {
  jsx: {
    babelConfig: {
      plugins: [
        [
          '@svgr/babel-plugin-remove-jsx-attribute',
          {
           "elements": ["path"],
           "attributes": [
               {
                 fill: 'black'
               }
           ]
          },
        ],
       [
          '@svgr/babel-plugin-remove-jsx-attribute',
          {
            elements: ['svg'],
            attributes: ['fill'],
          },
        ],
      ],
    },
  },
}
```

**Comment by adamstankiewicz** [comment]
@connorhaugh Awesome, thanks for doing some initial investigation. Very helpful. I will try to discuss with the Raccoon Gang engineers to see if we can prioritize a fix. I'll keep you informed.

cc @viktorrusakov @monteri When you have capacity, as some work that could be picked up next, I think this issue is worth prioritizing to ensure all the icons from `material-icons` behave properly with our `Icon`, `IconButton`, and `IconButtonToggle` components as it relates to variant/hover/focus styles as depicted in this issue as well as https://github.com/openedx/paragon/issues/1814

**Comment by connorhaugh** [comment]
Thanks for resolving this @adamstankiewicz  @viktorrusakov ! Paragon rules!
