### ISSUE TITLE
'Select all' button has incorrect label with applied filters in `DataTable`

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#1837]
**STR**
1. Go to [frontend-filtering-and-sorting example](https://paragon-openedx.netlify.app/components/datatable/#frontend-filtering-and-sorting)
2. Open filters dropdown and select "Orange tubby"
3. Select one of the rows

**AR**
- "Select all" button has "Select all 7" label even though there are only 2 rows displayed after applying filters
<img width="968" alt="image" src="https://user-images.githubusercontent.com/52399399/215549491-aaa963a1-b737-4e4d-ab0e-87fa45905b61.png">

**ER**
- "Select all" button has "Select all 2" label (in general case it should be "Select all {numOfFilteredRows}")
<img width="968" alt="image" src="https://user-images.githubusercontent.com/52399399/215549800-43d0c86b-facb-4718-a23b-d0a678b17628.png">

**Comment by viktorrusakov** [comment]
@adamstankiewicz for some reason I thought that after applying filters the `Select all` does not select anything, but I see that it's not the case now, false alarm, sorry 😞 

> After clicking "Select all 7" with same row selected (with filter applied NOT returning the selected row):
>
> Having it say "Select all 7" when only 1 result is returned given the applied filter seems incorrect, when the "Select all X" 
> should be applying only to the rows returned by any active filters.

that was also bothering me, I'll update the issue description to only include this point

**Comment by adamstankiewicz** [comment]
Sounds good! Thanks, @viktorrusakov.

**Comment by PKulkoRaccoonGang** [comment]
Issue: https://github.com/openedx/paragon/pull/2020
