### ISSUE TITLE
Update Forms examples on documentation site

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#1902]
Currently, old `Switch` and `Checkbox` components are displayed as examples on [Forms page](https://paragon-openedx.netlify.app/components/form/)
![image](https://user-images.githubusercontent.com/52399399/211493083-721efc63-2533-4c9f-9554-4bfbe31532eb.png)

**AC**
- make sure the latest versions of components are used in examples on `Forms` page in documentation site.

**Comment by PKulkoRaccoonGang** [comment]
Pull Request: [Form component](https://github.com/openedx/paragon/pull/1920)
