### ISSUE TITLE
Fix Button's inconsistencies with design

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#1903]
Quite a few issues with the `Button` component have been discovered lately, e.g. disabled `tertiary` buttons just disappears from the screen while `outline` variants have focus state when disabled (this is mainly concerns `edx.org` theme, but `openedx` theme also has some of these issues)
![image](https://user-images.githubusercontent.com/52399399/211494629-09a9c888-86b9-4827-bc9f-db6b8b0bafc5.png)

**AC**
- for `edx.org` theme compare current implementation of `Button` with [design specs](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=14061%3A5&t=MDdW897RudZRU46R-0) and make necessary fixes to `Button` component;
- for `openedx` theme fix obvious issues (e.g. `tertiary` button disappearing in disabled state)

**Comment by PKulkoRaccoonGang** [comment]
Pull Requests:
- [Paragon side documentation](https://github.com/openedx/paragon/pull/1910)
- [Brand EdxOrg](https://github.com/edx/brand-edx.org/pull/49)
