### ISSUE TITLE
Segment event always include empty string for search query in event properties

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1936]
The Icons page on the documentation website fires the following Segment event `openedx.paragon.icons-table.search` whenever the user finishes typing a search query via a debounced function. However, the debounced function is never re-computed when the `searchValue` changes in its `useCallback` dependency array, thus leading to an empty `value` event properties dispatched to Segment.

This limits our ability to get insights into which icons users are searching for on the Icons page.

**Acceptance Criteria:**
- [ ] Ensure the `openedx.paragon.icons-table.search` Segment event contains the search query that was just executed.
- [ ] Consider adding the number of search results given the specified query as an additional event property for this Segment event. This data would help query Segment events by number of results retrieved which may be helpful in answering the question of "Are users frequently searching for icons that don't exist in Paragon?".

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2011
