### ISSUE TITLE
Add Segment event for when the "Show code" block is opened/closed

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1937]
To better understand the documentation website usage, it'd be great to be able to know which code block examples are used the most. 

Example:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/2828721/214360558-4e1974bc-1e45-417b-ac7c-be8a4ec00baf.png">

**Acceptance Criteria**
- [ ] Ensure that when the "Show code example" or "Hide code example" buttons are clicked, we dispatch the following events:
  - `openedx.ui.example-code-block.opened`
  - `openedx.ui.example-code-block.closed`
- [ ] Ensure these events contain a way to identify which code block was opened in some way to be able to answer the question of which code block examples are most interacted with on the documentation website. For example, is there a way to generate a persistent, unique code block id?

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2002
