### ISSUE TITLE
Usage Insights "Summary" table's filter column shrinks when table row is expanded

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1942]
## With table row collapsed

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/2828721/214402875-78fe6cd5-930e-46da-bdb5-d40ab405196b.png">

## With table row expanded

<img width="953" alt="image" src="https://user-images.githubusercontent.com/2828721/214402968-7336214b-44fb-43fe-b405-aadc84dd4b61.png">

## Acceptance Criteria

- [ ] Ensure the `DataTable` filters sidebar width does not shrink when the table content area's row(s) are expanded in the Usage Insights "Summary" tab.
- [ ] Ensure the `DataTable` filters sidebar width does not shrink when the table content's area's row(s) are expanded in the `DataTable` documentation on the docs website.
- [ ] Ensure the `DataTable` filters sidebar width does not shrink in consuming applications when the table content area's row(s) are expanded.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2006
