### ISSUE TITLE
Ensure design tokens have a valid `type` attribute

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1947]
Per the official design tokens specification under review by the W3C Design Tokens Community Group, each design token should have a specified `type` attribute to categorize the design token to particular standard types.

See https://design-tokens.github.io/community-group/format/#types for more details.

For example, our color tokens should get a `"type": "color"` attribute whereas a spacing value (e.g., `0.5rem`) should get a `"type": "dimension"` attribute.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/1992
