### ISSUE TITLE
[discovery] Consider moving Paragon repository to NPM workspaces

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1949]
The Paragon repository has grown to include not just the SCSS and React components, but also other modules as well, including:

* Repository root (the packages for the SCSS styles and React components)
* `www` (documentation website) 
* `icons` (officially supported icons)
* `example` (example MFE to use for debugging/local QA in an MFE environment).
* `component-generator` (a CLI tool to generate new React components for Paragon)
* [...and soon `tokens`] (a collection of JSON design tokens and build configs/scripts)

Each of these modules defines its own `package.json` and `package-lock.json` files. In order to install all dependencies across the entire project, it requires engineer to run `npm install` in each module listed above. We have also introduced an NPM script `npm run install-all` intended to be a helper to install dependencies across all these modules.

In a world with NPM workspaces, however, we may be able to configure the repository to run a single `npm install` and have NPM workspaces intelligently install the `node_modules` across all modules listed above.

By doing so, most installed packages would likely be hoisted up to the root `node_modules` folder.

**Acceptance Criteria**

- [ ] Better understand whether NPM workspaces would be beneficial for developer experience within the Paragon repo and what the tradeoffs might be.
- [ ] Evaluate what it would take to migrate to NPM workspaces.
- [ ] If we do decide to move to NPM workspaces, draft a brief ADR describing the decision/rationale.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2190
