### ISSUE TITLE
Add `ChipCarousel` component

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1951]
There are valid use cases for a `ChipCarousel` component that exist in the platform today (notably, on [edX.org](https://edx.org)):

![Image](https://user-images.githubusercontent.com/2828721/214448821-2408f655-e894-4b95-9798-6b3fbd35d154.png)

There is a mock `Chip` carousel component [shown on the documentation website](https://paragon-openedx.netlify.app/components/chip/#chip-carousel) to demonstrate that `OverflowScroll` (and `useOverflowScroll`) may be used to create UI component-agnostic carousel-like behaviors.

This issue intends to create a true `ChipCarousel` component that mimics the behavior shown on the above edX.org example.

Depends on https://github.com/openedx/paragon/issues/1950

**Comment by monteri** [comment]
https://github.com/openedx/paragon/pull/2378
