### ISSUE TITLE
undefined/null fallback image logo source on Card working incorrectly

### ISSUE THREAD

**Issue by brobro10000** [openedx/paragon#1967]
The `fallbackLogoSrc` is incorrectly calling image URL when the `logoSrc` prop is not correctly fetching the image.

If the `fallbackLogoSrc` is not declared in the prop and the `logoSrc` fails, the component will attempt to render the fallbackLogoSrc infinitely 
<img width="752" alt="Screenshot 2023-01-27 at 9 37 04 AM" src="https://user-images.githubusercontent.com/82611798/215112638-d89c627b-2c59-48ca-abff-2c213a0df151.png">

If the `fallbackLogoSrc` retrieves either a null or undefined value, the same behavior will occur as above: the component will attempt to infinitely call the `fallbackLogoSrc`
<img width="756" alt="Screenshot 2023-01-27 at 9 39 39 AM" src="https://user-images.githubusercontent.com/82611798/215113061-9b418bcf-ecaf-4c07-aacb-7ca86b193877.png">
<img width="729" alt="Screenshot 2023-01-27 at 9 41 20 AM" src="https://user-images.githubusercontent.com/82611798/215113424-e07d7c19-edc8-486c-b59e-42dbf20c4140.png">

The resulting behavior on the card component is the image will render a blank white background in the logoSrc or show a blinking broken image link logo (blinking occurs due to attempted image src retrieval)
<img width="313" alt="Screenshot 2023-01-27 at 9 43 48 AM" src="https://user-images.githubusercontent.com/82611798/215113983-dc32284f-637b-4c67-8aea-26badad08f4c.png">

## **Acceptance Criteria**:
- [ ] Ensure when `logoSrc` image fails to load and no valid `fallbackLogoSrc` image is specified, it doesn't attempt to re-render the image infinitely.
- [ ] Ensure when `logoSrc` fails to load and no valid `fallbackLogoSrc` image is provided, the logo in `Card.ImageCap` should not appear as a white background with no image. Instead, we should hide the logo's wrapper altogether.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/1994
