### ISSUE TITLE
Ensure reference design tokens don't include `.value`

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1968]
Currently, all the reference design tokens include `.value` in their value strings, e.g.:

https://github.com/openedx/paragon/blob/9fb7e98edbba9eb07f8b1633d038b0bc91f2fd64/tokens/src/global/color.json#L29-L60

However, the `.value` is implied in the reference token string value. That is, `{color.primary.base}` should be equivalent to `{color.primary.base.value}`.

* Is there an explicit need in our implementation where `.value` _needs_ to be included in the reference token value strings?
* If so (presumably due to custom formatters/transforms), can those be refactored slightly to infer the `.value` as needed?

Further explanation, pretty much all the docs / examples about `style-dictionary` tend to not include `.value` in the reference token value strings.

**Comment by PKulkoRaccoonGang** [comment]
PRs:
Paragon - https://github.com/openedx/paragon/pull/1989
Brand - https://github.com/edx/brand-edx.org/pull/45

**Comment by adamstankiewicz** [comment]
Closing this issue as the [PR](https://github.com/edx/brand-edx.org/pull/45) is up for `@edx/brand` but we don't have an `alpha` release tag for `@edx/brand` to merge it yet. Also opened https://github.com/openedx/paragon/issues/2026 to track this work.
