### ISSUE TITLE
Rename Paragon Segment events

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1972]
# Description

Rename Segment events to follow a common convention:

```
openedx.paragon.{module}.{event descriptor}.{action} # action in past tense
```

Where `module` might be:
* `docs` (for the `www` folder)
* `functions` (for the `www/netlify/functions` folder)

See examples below. Find events throughout the repo by searching for `analytics.track`.

## Acceptance Criteria

- [x] `edx.paragon.generate-component` ➡ `openedx.paragon.functions.track-generate-component.created`
- [x] `openedx.paragon.icons-table.selected-icon.copied` ➡ `openedx.paragon.docs.icons-table.selected-icon.copied`
- [x] `openedx.paragon.icons-table.search` ➡ `openedx.paragon.docs.icons-table.search`
- [x] `openedx.paragon.menu.playground.visit_playground.clicked` ➡ `openedx.paragon.docs.menu.playground.visit_playground.clicked`
- [x] `openedx.paragon.elevation.generator.updated` ➡ `openedx.paragon.docs.elevation.generator.updated`
- [x] `Toggle Settings` (show) ➡ `openedx.paragon.docs.settings.opened`
- [x] `Toggle Settings` (hide) ➡ `openedx.paragon.docs.settings.closed`
- [x] `Theme change` ➡ `openedx.paragon.docs.settings.theme.changed` (with selected theme in event properties)
- [x] `Language change` ➡ `openedx.paragon.docs.settings.language.changed` (with selected language in event properties)
- [x] `ContainerWidth change` ➡ `openedx.paragon.docs.settings.container-width.changed` (with selected width in event properties)
- [x] `Usage Insights` (summary) ➡ `openedx.paragon.docs.insights.tabs.summary.clicked`
- [x] `Usage Insights` (projects) ➡ `openedx.paragon.docs.insights.tabs.projects.clicked`
- [x] `Usage Insights` (components) ➡ `openedx.paragon.docs.insights.tabs.components.clicked`
- [x] `Usage Insights` (hooks) ➡ `openedx.paragon.docs.insights.tabs.hooks.clicked`
- [x] `Usage Insights` (utils) ➡ `openedx.paragon.docs.insights.tabs.utils.clicked`
- [x] `Usage Insights` (icons) ➡ `openedx.paragon.docs.insights.tabs.icons.clicked`

**Comment by PKulkoRaccoonGang** [comment]
Pull Request: https://github.com/openedx/paragon/pull/1984
