### ISSUE TITLE
Ensure component examples and editable live code blocks are more perceivable

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1981]
For some component examples on the [documentation website](https://paragon-openedx.netlify.app/), it is difficult to differentiate between an example component preview and the documentation site's UI itself.

For example, Shopify Polaris renders [component examples](https://polaris.shopify.com/components/actions/button) in a light gray pane and includes a `Collapsible`-like pane around the live code editor:

<img width="906" alt="image" src="https://user-images.githubusercontent.com/2828721/231506901-7c6017cb-25d5-4558-a230-c4d18e91d368.png">

**AC**
- [ ] Ensure rendered components for each live code blocks are rendered on a light background (e.g., `gray-200`, `light-200`) to more clearly delineate where the code examples are on the page.
- [ ] Ensure collapsible for showing the live code editor is rendered as the large card style (i.e., `styling="card-lg"`).
- [ ] Ensure an icon (default `Collapsible` icon is likely fine) is rendered as an affordance to indicate that the live code block may be collapsed/expanded.
- [ ] Discovery: make a recommendation for implementing a "Copy" to clipboard (icon)button for live code blocks to allow engineers/consumers to more easily copy/paste from the component code snippets on the docs site. If implemented, ensure it gets a Segment event when clicked where the event name follows the same convention as other Segment event names throughout the docs site.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2194
