### ISSUE TITLE
Form.Checkbox body variants are miscolored.

### ISSUE THREAD

**Issue by connorhaugh** [openedx/paragon#1982]
AC:
- The form.checkbox danger and success variants should have the variant color as the body, not just the border. 

This is because:
https://github.com/openedx/paragon/blob/dce246d411de779e995ac16fab77bb8abf3c3142/src/Form/_Form.scss#L452 we set the background using an image. That image does not allow 1. for easy modification. 2. for variants to work. 
![Screen Shot 2023-01-30 at 2 41 20 PM](https://user-images.githubusercontent.com/49422820/215578893-5dd02f02-cc23-4b6b-878c-45339352a7b6.png)

**Comment by connorhaugh** [comment]
@adamstankiewicz  this is an interesting bug beginning to block our team. @rayzhou-bit is going to look into this, Do you have any ideas for easy solutions?

**Comment by adamstankiewicz** [comment]
> The form.checkbox danger and success variants should have the variant color as the body, not just the border.

@connorhaugh @rayzhou-bit What design spec are you referring to that shows the checkbox fill color changing based on the variant? 

In the official Paragon Figma library, there is no example spec for a checked success/danger checkbox so I wouldn't necessarily call this a bug per se: https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=5957%3A4083&t=mMUwLPqgyCHLvqFM-4

If a designer would like to propose the change described in this issue, they should also make the change in the Paragon Figma library directly as Paragon components are implemented to that spec and ideally bring it to Paragon Working Group.

Related, for consistency across input types, I would also consider whether this change should apply for `Form.Radio` as well:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/2828721/217277171-5262060b-b50f-441b-971c-d9e0326b7589.png">

**Comment by connorhaugh** [comment]
going to reach out to design about this. Thanks Adam!

**Comment by adamstankiewicz** [comment]
@connorhaugh Was there a decision made about this by your designer? It looks like the PR implementation was updated, but I don't see any cncrete next steps described in the Paragon Working Group Slack [thread](https://twou.slack.com/archives/C02NR285KV4/p1675805006360599) started by Jonathan. 

If so, can Jonathan update update the [official Figma spec](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=5957%3A4136&t=PteM799pGqqiZkYZ-4) for `Form.Checkbox` and `Form.Radio` to document this design decision there as well (i.e., there is no example in Figma currently of a checked success/danger checkbox)?

**Comment by adamstankiewicz** [comment]
@gabew1984 Can you take a look at this? We're looking for design clarification on whether the checked checkboxes (and radio buttons) in the success/danger state should be solid green/red. 

The implementation for this change is [complete](https://github.com/openedx/paragon/pull/2001); I'm just hoping for a final design sanity check this is the direction we want to go from a design perspective. It'd also be great if you and/or Jon Fay could add the checked success/danger states to Figma as there is nothing in the Figma that shows a fully checked checkbox. Thanks!

**Comment by gabew1984** [comment]
Agree @adamstankiewicz @connorhaugh that the danger and success variants should have the variant colors as the body, not just the border.
