### ISSUE TITLE
Refactor `tokens` file/folder structure to support additional theme variants

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2017]
# Description

The current structure of the `tokens` directory contains a top-level `src` folder containing all the tokens for the design system (e.g., `global`, `alias`, `component`). As described in https://github.com/openedx/paragon/issues/2014, these tokens are largely a combination of core tokens and tokens representing the values for the default "light" theme variant.

To be forward thinking to support a future dark mode (i.e., an additional theme variant), let's extract the core tokens out from the theme-specific tokens. I might recommend a folder/file structure similar to:

```shell
tokens/src/core/
tokens/src/themes/light/
tokens/src/themes/dark/ # in the future
```

By accomplishing this issue, consuming applications should be able to load the core Paragon styles independently from any theme-variant CSS variables. For example:

```html
<link rel="stylesheet" href="/dark.css" media="(prefers-color-scheme: dark)" />
<link
  rel="stylesheet"
  href="/light.css"
  media="(prefers-color-scheme: light)"
/>
<link rel="stylesheet" href="/core.css" />
```

# Acceptance Criteria
- [x] Ensure the global, alias, and component tokens defined in `./tokens/src/core/` are not specific to a particular theme variant (i.e., light or dark).
- [x] Ensure the global, alias, and component tokens defined in `./tokens/src/themes/light/` are only related to style properties relevant to a light theme variant (most likely color tokens).

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2069
