### ISSUE TITLE
documentation: Missing Button props 

### ISSUE THREAD

**Issue by brobro10000** [openedx/paragon#2111]
Within the [Paragon Button component](https://paragon-openedx.netlify.app/components/button/), the documentation located at the bottom of the page is not displaying all relevant prop types for the button component. 

![Screenshot 2023-03-02 at 12 19 31 PM](https://user-images.githubusercontent.com/82611798/222503676-7a76f276-d835-47f4-82c9-0b94b3c1654e.png)

An example of some of the missing props are `variant`, `iconBefore`, `iconAfter`. 

Although there are examples provided within the doc site, an explicit list of the capabilities/props available to a component would be relevant without having to look directly back at the component code to determine so.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2329
