### ISSUE TITLE
Upgrade Node JS from 16 to 18

### ISSUE THREAD

**Issue by abdullahwaheed** [openedx/paragon#2143]
**Abstract**
Node 16's support will end on [September 11, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol/). So we have to upgrade node JS to v18 before that.

**Extras**
Project should use `.nvmrc` to have a consistent node version
We have to update Readme accordingly.

[Upgrade Node JS from 16 to 18](https://github.com/openedx/platform-roadmap/issues/243)

**Comment by adamstankiewicz** [comment]
Closed via https://github.com/openedx/paragon/pull/2227
