### ISSUE TITLE
Add direct links to component insights from component documentation pages

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/paragon#2179]
For example, it would be really cool if when visiting https://paragon-openedx.netlify.app/components/actionrow/ there was a link to the insights page for `ActionRow`

With this implemented, potential consumers of the component could:
* Determine if a component is "prod ready" by seeing how many places it's being used
  * Could be really cool to have instance count directly displayed on the component documentation page, this would make the answer to this question "glanceable" and not require a click
* Have discoverable access to "real world" usage examples that go beyond the examples from the documentation

Things that would need to be built out for this to work:
* Ability to link to components in usage insights (right now users must rely on the search box)

```[tasklist]
### Acceptance Criteria
- [ ] Understand what it would take to link component pages to the appropriate spot in "Usage Insights" (e.g., skip links like https://paragon-openedx.netlify.app/insights/components#ActionRow to scroll to specific component heading).
- [ ] Understand what it would take to surface "Usage Insights" data into component pages on the documentation website.
- [ ] File a new GitHub issue with a recommendation for what to implement as a solution.
```

**Comment by adamstankiewicz** [comment]
This is a great idea, @brian-smith-tcril! Thanks for the suggestion. Let's treat this as a discovery task for Raccoon Gang to see what might be possible technically to bring some of the "Usage Insights" data into component documentation pages, and/or have the component documentation pages link to the appropriate place in "Usage Insights".

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2201
