### ISSUE TITLE
Misaligned form validation text with icon

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2197]
https://paragon-openedx.netlify.app/components/form/form-group/

The `Form.Group` component allows you to include a form validation message under the `Form.Control`. However, the icon (either an "X" or a check) is not vertically aligned with each other (in both Open edX theme and edX.org theme):

<img width="960" alt="image" src="https://user-images.githubusercontent.com/2828721/232477618-32186bfc-5968-42ff-b366-71ab4e699011.png">

Looks like it has a style property to `align-items: center;` but the element has `display: block;` so it doesn't take affect:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/2828721/232477764-043fa0bf-fb7f-48e3-8f5d-8dd39a397629.png">

```[tasklist]
### Tasks
- [ ] Ensure the form validation icon and message are vertically aligned.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2202
