### ISSUE TITLE
Active tab background color is white which may not be expected if rendering `Tabs` on a non-white background

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2211]
https://paragon-openedx.netlify.app/components/tabs/

The active tab styling doesn't quite match the Figma spec given it has a white background for its hover/focus states. It should look more like the following Figma spec: https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=7542-24823&t=t4PotStnrmsyQSoH-4

<img width="587" alt="image" src="https://user-images.githubusercontent.com/2828721/233634898-bee1caf4-1601-4f70-bab8-e8a59edcfb2a.png">

As a result, when `Tabs` are rendering a non-white background, the active tab always having a white background may not be intended/expected/desired by consumers.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2222

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2222
