### ISSUE TITLE
`Card.Status` does not quite support an `ActionRow` in its children

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2214]
When rendering the following:

```jsx
<Card.Status icon={Warning} variant={variant}>
  <p>Warning lorem ipsum dolor sit amet</p>
  <ActionRow>
    <Button size="sm">Contact</Button>
  </ActionRow>
</Card.Status>
```

the rendered output is as follows:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/2828721/233677810-1c8a5f34-613a-4015-9d20-ee5427bdb030.png">

The button appears to be misplaced, with the expectation that its parent `ActionRow` expands the full width of `Card.Status`, but it does not:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/2828721/233678061-5e9cb5bc-3312-496d-847f-c961ae9df17c.png">

The expected rendered output of `ActionRow` within `Card.Status`:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/2828721/233678346-36d7cb53-2244-4bb2-b51e-2655931b83e7.png">

**AC**
- [ ] Ensure that child components can expand the full width of `Card.Status` such that a button rendered within `ActionRow` is fully right-aligned.

**Comment by monteri** [comment]
https://github.com/openedx/paragon/pull/2219
