### ISSUE TITLE
Clean up errors in tests

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2225]
Currently `npm run test` produces a lot of `console.error` logs in its output, e.g

![image](https://user-images.githubusercontent.com/52399399/234188406-746e3c26-1c6f-4549-9c27-167e9da8ec52.png)

they are mostly invalid prop warning, but there are other types also. This indicates that some of our tests might just be invalid (if we pass a wrong prop in the test, then we're not really testing expected behaviour).

```[tasklist]
### AC
- [ ] Ensure  `npm run test` command does not produce any errors in the logs
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2226
