### ISSUE TITLE
Remove usage of deprecated lifecycle methods

### ISSUE THREAD

**Issue by thallada** [openedx/paragon#223]
This will involve changing our components to use new component lifecycle methods since the ones we use now are deprecated and "`UNSAFE`".

`componentWillUpdate`:
- [ ] `Dropdown`

`componentWillReceiveProps`:
- [ ] `StatusAlert`
- [ ] `asInput`
- [ ] `Fieldset`
- [ ] `Modal`
- [ ] `CheckBox`

All consuming IDAs will need to upgrade to 16.3 as well before they can pull in Paragon v4.

**Comment by jaebradley** [comment]
Can you give a list of the out-of-date component lifecycle methods and the components that need to be updated?

**Comment by thallada** [comment]
@jaebradley see [this React blog post about the lifecycle method changes](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html). Basically, these methods will be deprecated in React 16 and will be renamed to `UNSAFE_[name]` in React 17:

- `componentWillMount`
- `componentWillReceiveProps`
- `componentWillUpdate`

`Dropdown` uses `componentWillUpdate`. And, `StatusAlert`, `asInput`, `Fieldset`, `Modal`, and `CheckBox` all use `componentWillReceiveProps`.
