### ISSUE TITLE
`Tabs` component renders anchor tag as a child of another anchor tag

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2232]
Currently when there are too many `Tab` components to fit into the `Tabs` container width we render a `More...` (see [example](https://paragon-openedx.netlify.app/components/tabs/#responsive-support) on the docs site) tab that shows the rest of the tabs, which results in nesting of `a` tags because each `Tab` is rendered as an `a` tag (including the `More...` tab). According to W3C spec nesting of `a` tags is not allowed, so we should fix that.

![image](https://user-images.githubusercontent.com/52399399/234874399-76346d82-0b99-4204-b734-3c892dc09f43.png)

```[tasklist]
### Tasks
- [ ] Consider how we might render `More...` tab as a button instead of an anchor and implement the solution
```

**Comment by PKulkoRaccoonGang** [comment]
Resolved in https://github.com/orgs/openedx/projects/43?pane=issue&itemId=27411598
