### ISSUE TITLE
Finish FontAwesome deprecation

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2235]
We started [deprecation](https://github.com/openedx/paragon/pull/1158) of font-awesome a while ago, but didn't complete it as it would introduce breaking changes for the consumers. With design tokens release it seems like it's a good opportunity to finish this deprecation process as `v21` of Paragon will have a lot of breaking changes anyway (e.g., we finally removed all deprecated components).

```[tasklist]
### AC
- [ ] Completely remove font-awesome usage in the `alpha` branch
```

**Comment by adamstankiewicz** [comment]
Currently still used in `IconButton` (default icon is from font-awesome). Would have been a breaking change so we originally deferred.

We did add `console.error` to warn consumers of the deprecation to encourage them to migrate off.
