### ISSUE TITLE
Add a "Leave feedback" hyperlink

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2243]
We would like a mechanism to collect feedback from the Paragon docs site. A trivial way to do this is to add a link to create a new GitHub issue, e.g., https://github.com/openedx/paragon/issues/new?title=%5Bparagon-openedx.netlify.app%5D%20Feedback%20(on%20%2Frelative%2Fpath)&amp;labels=docs

The "Leave feedback" link should navigate user to open a GitHub issue with the title filled out:

`[paragon-openedx.netlify.app] Feedback (on /relative/path)` where "/relative/path"` is the URL path the user is on at the time of clicking the "Leave feedback" link

See https://polaris.shopify.com/tokens/color as an example.

More feedback mechanisms to come in later issues :) 

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2828721/235172073-53e3342b-5507-4f6c-818d-07a4920a395e.png">

<img width="862" alt="image" src="https://user-images.githubusercontent.com/2828721/235172682-6a295d9a-17e2-4d86-b47a-510d5deaf82d.png">

```[tasklist]
### Acceptance Criteria
- [ ] Add "Leave feedback" link to the bottom of all pages (components, guides, etc.). The link should be styled as a gray and rendered under a `<hr />` (see screenshot 1).
- [ ] Add "Leave feedback" link in the footer (see screenshot 2).
- [ ] When links are clicked, track a Segment event conforming to Segment event name conventions. No event properties necessary.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2313
