### ISSUE TITLE
Algolia reindex issue

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2250]
Algolia reports that there is a blocking issue with reindexing of data (likely because of the docs site redesign, since we removed a lot of link from the home page)
![image](https://user-images.githubusercontent.com/52399399/235842624-23c4e75a-a768-43be-8955-f6a797285786.png)

```[tasklist]
### DoD
- [ ] Adjust algolia configuration, so that it doesn't cause issues with reindexing
```

**Comment by adamstankiewicz** [comment]
Thanks for fixing this, Viktor!
