### ISSUE TITLE
[docs] "Copy" button on live code editor resets component preview and copies initial state

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2263]
The "Copy" icon button on live code editors, when clicks, resets the component preview to its initial state on page load. Additionally, it appears the copied code is the initial state, not the user's custom input.

This limits the utility of the feature as users may specifically want to copy the code after making custom changes.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2283
