### ISSUE TITLE
Extend `@edx/typescript-config` in the tsconfig.json files

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2266]
We recently published https://github.com/openedx/typescript-config (`@edx/typescript-config`) as a new NPM package to be the standard base TypeScript config (IIRC we borrowed it pretty much verbatim from the existing tsconfig.json in Paragon).

Now, that it exists, we should use it in this repository. There are 2 tsconfig.json files in this repo; they should likely extend `@edx/typescript-config` at this point and buy into any future changes to the base config.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2309
