### ISSUE TITLE
Add ability to use different `Button` variants in `SelectMenu` component

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2275]
Currently `SelectMenu` uses `tertiary` and `link` `Button` variants internally and does not provide the API to change it, but according to [design](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?type=design&node-id=6594-11625&t=XSPdELT5ztrrIjF1-0)  consumers should be able to use any of our button variants.

```[tasklist]
### AC
- [ ] Ensure `SelectMenu` provides an API to use different `Button` variants (likely through a new prop)
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2291
