### ISSUE TITLE
Use `MailtoLink` as a `Button`

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2278]
# Description

It's possible to use `Button` as a `Hyperlink` such that the button text color is still correct given its background (e.g., white on a darker background):

```jsx
<Button
  as={Hyperlink}
  destination="https://edx.org"
  target="_blank"
  size="sm"
>
  Contact administrator
</Button>
```

A similar use case is to render a `Button` as a `MailtoLink`. However, in this case:
* The text color is not correct (i.e., should be white on a primary background).
* The entire button should trigger the `MailtoLink`, rather than just the inner `a` tag.
* The button text appears to be slightly off center vertical compared to the `Button` as a `Hyperlink`.

```jsx
<Button
  as={MailtoLink}
  to={['first@example.com', 'second@example.com']}
  target="_blank"
  size="sm"
>
  Contact administrator
</Button>
```

<img width="783" alt="image" src="https://user-images.githubusercontent.com/2828721/236829800-d5874ff1-8fc4-4457-a2df-7d72db81035d.png">

[Playground Demo](https://paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcIA8BlALgQzAawARQEsAnGMNAiAOwF4AdEACwiIIC8rMAbe3AcwwAO1YACYAvgD5alXLiQAhAK5o0VabNkYAzsIASATwEwinApWxj1G2FvKUM5KnUYqBW%2BAHoPMKAA8AdMy89FaymES8MGjOAPoARpwY5iEyGlpsMM5aALYpGlKpsgDCHFhouBhQ2WYEtkQOzFZIHkoqVAWyCsqqlKEVOsAAshgEnKoAMmYWfarCANoA5NqY5gQwAO4EYKwAAiKK-pDZCwA0uEu8tknYBDu82SOchxDHALqWhbjhkdH08YnJEB9dKsTL0HJ5WQdDQlSiYMgVKo1OoNIhNFrddrSZroLDYCQgE4gTZQNAMLQIOYAdgAbAAOd5AA)

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2326
