### ISSUE TITLE
`onClick` prop does not work in `From.AutosuggestOption` component

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2284]
`Form.AutosuggestOption` has a `onClick` prop, but if you pass a function there it is never triggered.

![image](https://github.com/openedx/paragon/assets/52399399/471c0779-ebd7-42ab-8aca-526b695be51b)

```[tasklist]
### AC
- [ ] Ensure `onClick` function gets called each time a `Form.AutosuggestOption` is clicked
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2286
