### ISSUE TITLE
Bootstrap Brand Icons

### ISSUE THREAD

**Issue by gabew1984** [openedx/paragon#2310]
Add only the Bootstrap Brand icons to Paragon for use in social sharing contexts. 

Notes from Paragon Working Group:

- [Use Bootstrap Icons Brand icons](https://icons.getbootstrap.com/)
- Brand Icons should have its own page on the docsite under the "Foundations" category
- Ensure the icons default pixel dimensions match the Material Icons library (24x24px default dimensions)
- [Figma](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?type=design&node-id=48478%3A84270&t=nbSQecA5JQvuCQvU-1)

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2224
