### ISSUE TITLE
[Usage Insights] Component type is missing in subcomponents

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2318]
On the [Usage Insights page](https://paragon-openedx.netlify.app/insights) subcomponents have blank values in the `Type` column

![image](https://github.com/openedx/paragon/assets/52399399/5d897847-05e3-4394-89af-520520b6477e)

```[tasklist]
### AC
- [ ] Ensure subcomponents have `Component` type in Usage Insights table
- [ ] Verify that all other types are correctly identified (e.g. hooks, functions)
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2267
