### ISSUE TITLE
Migrate tests from `enzyme` to `react-testing-library`

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2325]
During [upgrade to React 18](https://github.com/openedx/paragon/pull/2224) it was discovered that `enzyme` has no support for React 18 and it breaks a lot of our tests. Furthermore, there is no plans of [making `eznyme` adapter for React 18](https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl), meaning our tests will never pass with React 18 (unless we use some unofficial adapter like [this one](https://www.npmjs.com/package/@cfaester/enzyme-adapter-react-18), which we really shouldn't be doing).

We can solve this problem by fully migrating our tests to react-testing-library and/or react-test-renderer, which we already use in a bunch of our tests. React-testing-library supports React 18 starting from [v13.0.0](https://github.com/testing-library/react-testing-library/releases/tag/v13.0.0) and nowadays it is recommended tool for testing React applications. This would unblock our upgrade to React 18.

```[tasklist]
### AC
- [ ] All of the tests that use `enzyme` are migrated to using `react-testing-library` and/or `react-test-renderer`. Overall project coverage should not be lowered in the result. All existing test cases should still be covered and passing.
```

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2581
