### ISSUE TITLE
Remove white background on `Stepper.Header`

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2342]
The `StepperHeader` sub-component as part of `Stepper` includes a background color of white. However, when using a `Stepper` on a non-white background, the white background color of `StepperHeader` is unintentional:

<img width="901" alt="image" src="https://github.com/openedx/paragon/assets/2828721/1a170d3c-aa77-4dd9-a256-ea90faf22408">

```[tasklist]
### Tasks
- [ ] Ensure `StepperHeader` has no background color defined (transparent), such that the container's background color in which the `Stepper` is rendered can be seen through the `StepperHeader`.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2358
