### ISSUE TITLE
[paragon-openedx.netlify.app] Feedback (on )

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2343]
The "(on )" portion of the generated title from the "Leave feedback" link from the docs site appears to not be including the current relative path of the page the user was on (i.e., see this issue's generated title).

I created this issue by clicking the "Leave feedback" link from https://paragon-openedx.netlify.app/components/actionrow/.

```[tasklist]
### Tasks
- [ ] Ensure the "(on )" portion of the generated issue title comes through.
- [ ] Ensure the "Leave feedback" hyperlink is only clickable when the user's cursor is explicitly over the "Leave feedback" words; currently, the remaining whitespace to the right "Leave feedback" acts as the click target for the link.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2359
