### ISSUE TITLE
Missing design token for `$rounded-pill`

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2344]
When trying to use the design tokens compiled CSS from `@edx/paragon` in frontend-app-profile, there was a drop-in replacement for every SCSS variable and media query except for `$rounded-pill`. On the `alpha` branch, it doesn't appear we have any tokens that specify a `source: '$rounded-pill'`, which seems to indicate we may not have a design token to go along with `$rounded-pill`.

```[tasklist]
### Tasks
- [ ] Check whether we're missing a design token for the current state `$rounded-pill` SCSS variable; if so, add one.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2361
