### ISSUE TITLE
Update "Colors" page in Paragon docs site to reflect design tokens and CSS variables

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2345]
The ["Colors" foundation page](https://paragon-openedx.netlify.app/foundations/colors) on the Paragon docs site lists and displays each of the SCSS variables in the design system, showing the resulting HEX value.

With design tokens, we no longer want to show the SCSS variables here in favor of either showing the CSS variable or the design token name.

There is also guidance on this page around SCSS color usage that will no longer be relevant in a world with design tokens and CSS variables.

```[tasklist]
### Tasks
- [x] Understand how we can modify the "Colors" page using data sourced from the design tokens and/or CSS variables.
- [x] Make appropriate changes to the documentation to reflect the new state of the world with CSS variables and design tokens.
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2376
