### ISSUE TITLE
Try to find additional missing SCSS variables in design tokens

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2347]
Similar to the case of a missing design token for `$rounded-pill`, let's use this issue as a sanity check around trying to find any other potentially design tokens missing for existing SCSS variables.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2364

**Comment by adamstankiewicz** [comment]
Closed via https://github.com/openedx/paragon/pull/2364
