### ISSUE TITLE
Errors thrown in tests produce log messages even with console is stubbed out. 

### ISSUE THREAD

**Issue by Mjloturco** [openedx/paragon#236]
https://github.com/edx/paragon/pull/153 this PR introduces some errors that get thrown in the Modal when an invalid prop is passed in. A test was added to test that error functionality, but it clutters the logs (despite all tests passing), this could be cleaned up hopefully.

**Comment by adamstankiewicz** [comment]
Closing this issue as the `Modal` component is deprecated and will soon be removed.
