### ISSUE TITLE
Page not found after following link to React-Bootstrap site documentation

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2365]
Paragon site documentation contains links to components from React-Bootstrap site documentation. After clicking on these links, pages are displayed as "Page not found".

For example [Badge component](https://paragon-openedx.netlify.app/components/badge/):

![image](https://github.com/openedx/paragon/assets/93188219/a0da63cd-8e97-4570-9d9f-0dbe6a0c5750)

![image](https://github.com/openedx/paragon/assets/93188219/eaea6368-0dd6-4372-aef5-5bebc5f658eb)

```[tasklist]
### Tasks
- [ ] Ensure that all links on the Paragon documentation site lead to the correct React-Bootstrap URL.
- [ ] Check out the other links on the paragon documentation site.
```

**Comment by adamstankiewicz** [comment]
Let's consider expanding the scope of this issue to ensure any link to have to `react-bootstrap`'s website points to the correct _version_ of `react-bootstrap` that `@edx/paragon` relies on. I believe most (if not all) our links to `react-bootstrap`'s website are to the latest version (Bootstrap 5, when we're on Bootstrap 4).

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2394
