### ISSUE TITLE
The button outline in the Tabs component is displayed incorrectly

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2368]
After updating the design of the [Tabs](https://paragon-openedx.netlify.app/components/tabs/#pills-usage) component, there is an outline without rounding in the "Pills usage" example.
I suggest that we match the outline with the button.

Example:
![image](https://github.com/openedx/paragon/assets/93188219/20de0606-da58-4425-b65c-9abf5f2cc250)

Example Button component:
![image](https://github.com/openedx/paragon/assets/93188219/d9cb4cac-7ab3-41da-840a-7f8211dcdaa6)

```[tasklist]
### Tasks
- [ ] Ensure the button outline matches the button rounded.
```

**Comment by anjali29singh** [comment]
is this issue open to contribute  ?

**Comment by PKulkoRaccoonGang** [comment]
Resolved in https://github.com/openedx/paragon/issues/2370
