### ISSUE TITLE
Odd trapezoid-like underline on active tab in `Tabs` component

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2370]
![Image](https://github.com/openedx/paragon/assets/2828721/73bec607-bcf4-4e20-80c9-a9a024b67fe5)

**Comment by lemondevxyz** [comment]
Hello,

Would the desired behaivor look like this?
![Screenshot from 2023-06-11 01-12-55](https://github.com/openedx/paragon/assets/62130041/7d1aa1c1-8ba7-408c-9a3f-17327d35ce34)

**Comment by adamstankiewicz** [comment]
@monteri It should reflect what's shown in the Figma for the `Tabs` component [here](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?type=design&node-id=7542-24949&t=FiurCAf18dP6Ao8o-4), which matches the screenshot shared above by @lemondevxyz :

![Image](https://github.com/openedx/paragon/assets/2828721/f2584578-5f6c-473f-b29e-040e12766748)
