### ISSUE TITLE
[paragon-openedx.netlify.app] Feedback (on /components/alert/)

### ISSUE THREAD

**Issue by gabew1984** [openedx/paragon#2373]
## Improvements

Please add a "Leave feedback" button to the top of the component page template, and style the button as an "**small, outline primary button**".
![Screenshot 2023-06-12 at 11 20 10 AM](https://github.com/openedx/paragon/assets/14075470/8ae7faed-9f92-418f-a12f-89d86c4849af)
![Screenshot 2023-06-12 at 11 18 14 AM](https://github.com/openedx/paragon/assets/14075470/55af11a2-ef7e-4b67-89c3-7054ab7332fe)

Migrate existing "Leave feedback" hyperlink to a similar button as at the top of component page.

**Comment by adamstankiewicz** [comment]
Related issue: https://github.com/openedx/paragon/issues/2366

**Comment by PKulkoRaccoonGang** [comment]
> Related issue: #2366

@adamstankiewicz This is for the alpha branch.

**Comment by adamstankiewicz** [comment]
Closed via https://github.com/openedx/paragon/pull/2395
