### ISSUE TITLE
Duplicate component names in style imports file

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2387]
Curious moment. If the style files of each component are renamed to `index.scss`, then it becomes possible to remove the duplication of names in the global `index.scss` file.

For example:

<img width="401" alt="image" src="https://github.com/openedx/paragon/assets/93188219/2dd736b5-6c0a-4d4f-947c-5ffa5e65f134">

<img width="353" alt="image" src="https://github.com/openedx/paragon/assets/93188219/42b34264-458a-40fc-bca2-ad5adc6694b0">

* Rename styles with `index.scss`.
* Update component generator to account for changes.

**Comment by adamstankiewicz** [comment]
Hello @anjali29singh! I've assigned this issue to yourself 😄 Let us know if you have any questions/difficulty working on this issue.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2408
