### ISSUE TITLE
Non-transparent background for pagination elements

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2391]
Perhaps we need to consider adding a transparent background for Pagination (similar to the [recent task for Stepper.Header](https://github.com/openedx/paragon/issues/2342))

![image](https://github.com/openedx/paragon/assets/93188219/c8b3d1f1-34e5-4dfe-bd3b-44843d242958)

**Comment by viktorrusakov** [comment]
Fixed in https://github.com/openedx/paragon/pull/2837
