### ISSUE TITLE
[BD-46] Some problems in the Safari browser

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2432]
When checking the Paragon components when using the [Safari browser](https://www.apple.com/safari/), problems were found:
- there is no outline for the [Buttons](https://paragon-openedx.netlify.app/components/button/) (OpenEdx, Brand themes);

- accessibility problems (it is not possible to navigate through the elements of the component using the Tab key, this problem does not exist in the Chrome browser);
- there is no possibility to manually adjust the height of the [Form.Control](https://paragon-openedx.netlify.app/components/form/form-control/#textarea-autoresize) component with the textarea type;
- clicking behavior on [IconButton](https://paragon-openedx.netlify.app/components/iconbutton/#inverted-colors) with `invertColors` prop differs from Chrome browser

**Comment by adamstankiewicz** [comment]
@PKulkoRaccoonGang Appreciate you guys doing some cross-browser testing in Safari! 

I've added an `epic` label to this issue. I might recommend filing each of these items as a separate GitHub issue with a bit more detail that can be tracked and worked on independently, possibly with screenshots and/or screen recordings where applicable. Thanks!

**Comment by monteri** [comment]
https://github.com/openedx/paragon/issues/2781
https://github.com/openedx/paragon/issues/2782
https://github.com/openedx/paragon/issues/2783
https://github.com/openedx/paragon/issues/2784
https://github.com/openedx/paragon/issues/2785

**Comment by monteri** [comment]
https://github.com/openedx/paragon/issues/2783
