### ISSUE TITLE
[alpha] Rename custom media query output to ensure `pgn` namespace is the prefix

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2444]
The design tokens build process generates the following file: https://github.com/openedx/paragon/blob/alpha/styles/css/core/custom-media-breakpoints.css

It contains `@custom-media` definitions such as:

```css
@custom-media --max-pgn-size-breakpoint-xs (max-width: 576px);
```

However, the `min` and `max` substrings are coming before the `pgn` prefix. 

To ensure consistency across all tokens/variables available to consumers (e.g., `--pgn-color-primary-500`), we should ensure the `@custom-media` query variables include `pgn` as the prefix, e.g.:

```css
@custom-media --pgn-size-breakpoint-min-width-xs (min-width: 0);
@custom-media --pgn-size-breakpoint-max-width-xs (max-width: 576px);
@custom-media --pgn-size-breakpoint-min-width-sm (min-width: 0);
@custom-media --pgn-size-breakpoint-max-width-sm (max-width: 768px);
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2495

**Comment by adamstankiewicz** [comment]
Closed via https://github.com/openedx/paragon/pull/2495
