### ISSUE TITLE
Extend Form.Control with input mask

### ISSUE THREAD

**Issue by monteri** [openedx/paragon#2458]
Input mask can nr useful in cases with phone number, credit card, date.
There are existing solutions for React that can be either integrated with `Form.Control` or partially taken to create own input mask functionality.
Example:
[react-input-mask by sanniassin](http://sanniassin.github.io/react-input-mask/demo.html) 

Considered enough of a PITA for users where it’s a WCAG concern. (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel)

**Comment by PKulkoRaccoonGang** [comment]
PR: (DRAFT) https://github.com/openedx/paragon/pull/2626
