### ISSUE TITLE
Card.ImageCap does not have top rounded corners

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2473]
### Current state of `Card.ImageCap`

The `Card.ImageCap` does not have rounded corners on the top as is expected and was previously implemented.

<img width="300" alt="image" src="https://github.com/openedx/paragon/assets/2828721/93c735b7-cc3d-40de-805a-63bd46a3e22e">

[Playground Demo](https://paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcIA8BhAhgJygcQwSygD4AdAOwAJzVMizLLqsA6ASQFs0BzGdABzvqUAzhjABeYiAAWAFxm8h8APRLeeMEICubJrykQZEIUoDMANgAMSgEwWrkgYJFgAggBsZEkOizk8HbgcKeiUSYIYfKCYACRg0WAxyGTwZNxgvSPIAFRS0yXJQxypIpgBlGDBkiFIwwUosqTwhP2a0cjAaciEKqtImchYZdrQKSFIZNDwKEYBPGUbSTnIAI00hzS00NzcZpJgADxkAGnI2tybj8ghE86EhiAAzcnPSAGshfoBZTQ88XjSuj08NVmlI0AA3GCnYa%2BKB4cEEGCJZYwGQAdxgMAo8xgOiKSCUJXKlWBNXxJQAYhADEjanUkAAhNaGGouEnVcgARgJTLk1TpDEJNCYVJpGDpBMiYUlNFwBEIICOIBxbBgQgQAG0QDAoAANJjXTggAC6SrRBHm6vgGoAnDbrMaAL5AA)

### Expected state of `Card.ImageCap`

Note the rounded corners on top the image:

<img width="381" alt="image" src="https://github.com/openedx/paragon/assets/2828721/057d340c-b318-4fd8-b2be-1bfd5e844193">

```[tasklist]
### Tasks
- [ ] Ensure `Card.ImageCap` styles have top rounded corners, matching the [Figma spec](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?type=design&node-id=3461-9&mode=design&t=WvVURHJGOpToHgg3-4).
```

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2496

**Comment by adamstankiewicz** [comment]
Closed via https://github.com/openedx/paragon/pull/2496
