### ISSUE TITLE
[paragon-openedx.netlify.app] Feedback (on /components/truncate/)

### ISSUE THREAD

**Issue by KristinAoki** [openedx/paragon#2475]
## Bugs

When using the truncate component in a card it does not properly truncate the text if there are no spaces or the words are exclusively separated by underscores. This forces the cards to expand past their set column width.

#### Expected

<img width="349" alt="Screenshot 2023-07-26 at 9 31 21 AM" src="https://github.com/openedx/paragon/assets/42981026/0204c4bd-0f03-4bc9-8a33-c05d7bf65d6f">

<img width="349" alt="Screenshot 2023-07-26 at 9 27 48 AM" src="https://github.com/openedx/paragon/assets/42981026/4d42a796-2055-4622-8dd7-ac1dcf0d915e">

#### Actual
<img width="480" alt="Screenshot 2023-07-26 at 9 05 54 AM" src="https://github.com/openedx/paragon/assets/42981026/afe39de2-32bb-42ba-a9f4-b2c1de621e2b">
<img width="480" alt="Screenshot 2023-07-26 at 9 08 36 AM" src="https://github.com/openedx/paragon/assets/42981026/b9be12b8-61ed-4c48-aeb0-7a788cc5863d">

**Comment by khudym** [comment]
PR:https://github.com/openedx/paragon/pull/2584
