### ISSUE TITLE
CLI improvements

### ISSUE THREAD

**Issue by monteri** [openedx/paragon#2483]
I place here comments from initial PR for CLI https://github.com/openedx/paragon/pull/2460

1. [suggestion] This can totally be deferred, but an idea: make the --no-save option configurable/overrideable such that the command can be run where this npm install does save. The default should be --no-save, though.

I'm thinking of a possible use case where the Paragon CLI could be used in infrastructure/deployment code to install the @edx/brand aliases rather than the infrastructure/deployment code needing to do the npm install themselves (might be easier to simply run paragon install-theme during the build+deploy process 🤷‍♂️). Ah, but in this case, the user input wouldn't be possible.

Let's defer on this comment for now but come back to it at some point. I think to support the infrastructure/deployment code use case, we'd need a variant of the paragon install-theme CLI command that allowed its user to pass --brand (or similar) as an argument to avoid needing to provide user input.

2. [suggestion] To have better observability in how consumers make use of these commands, I might recommend we try dispatching a Segment event describing which command is used and how, similar to how we have sendTrackInfo in the component generator tool.

Speaking of the component generator, we may also want to backlog an issue to migrate its current implementation into this new Paragon CLI as a distinct command (not in scope for this PR).

3. [curious/suggestion] Is there a way to list out all possible CLI commands as a hint for users on what commands are available to use? In a similar vein, is there or should there be a paragon help type of functionality? This, too, could likely be deferred as a separate feature addition.

**Comment by adamstankiewicz** [comment]
@monteri It may be helpful to split these out into there own individual GitHub issues? I believe they could mostly be worked on independently once the foundations of the CLI tool are in place. We could keep this issue around as an "epic" and link it to the other issues, if you'd like.

**Comment by viktorrusakov** [comment]
I think all of the items from this issue were implemented as part of other isuess, so I'm closing this as done
