### ISSUE TITLE
slider in color picker results in `#NaNNaNNaN` when sliding after entering invalid hex

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/paragon#2524]
![picker](https://github.com/openedx/paragon/assets/112954497/1e24a4ac-6fcb-4b38-b023-71eaad69f1e8)

## Repro steps
* go to color picker page https://paragon-openedx.netlify.app/components/colorpicker/
* select `#badcolor` picker (or enter `#badcolor` into any of the other pickers)
* slide the bar

### Observed behavior
* `#NaNNaNNaN` appears in hex box

### Expected behavior
* not exactly sure, probably top right corner selected so the color matches what appears on the slider

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2646
