### ISSUE TITLE
[alpha] Changes in Nav tabs UI

### ISSUE THREAD

**Issue by dcoa** [openedx/paragon#2526]
## Bug

I've been testing Paragon alpha in different MFEs, one of them Authn, and the tabs in Nav Component have some differences between the production view and the alpha version.

[nav-alpha.webm](https://github.com/openedx/paragon/assets/66016493/ed0008be-2fdb-4025-be61-5bb87df399b9)

|     | Prod    | Alpha |
| ------| -------- | ------- |
| border bottom widh  | 2px   | 3px |
| Focus | no border   | border |

The border-bottom has a strange end

**Expected behavior:**  

[nav-prod.webm](https://github.com/openedx/paragon/assets/66016493/435d606f-6f37-447e-b1ea-cbb9922827d1)

**Comment by adamstankiewicz** [comment]
Thanks for reporting this issue, @dcoa! We've prioritized a fix for our next Paragon sprint.

**Comment by PKulkoRaccoonGang** [comment]
@dcoa Thank you for your message. Just recently we carried out a [small redesign](https://github.com/openedx/paragon/issues/2211) of the Tabs component. Now the Tabs look according to the [design](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?type=design&node-id=14061-24&mode=design&t=qBttqbNS3dGjNu5W-0) developed by the Paragon team. Most likely, when you noticed the differences in the design of the Tabs, the production version did not yet have new changes.

**Comment by viktorrusakov** [comment]
This is result of `Tabs` redesign, closing this issues as this is the expected result (it's actually now on prod of edx.org as well)
