### ISSUE TITLE
Card loading state

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2528]
It appears the `Card` skeleton loading state when the `isLoading` prop is passed is no longer working, at least on the documentation website:

<img width="947" alt="image" src="https://github.com/openedx/paragon/assets/2828721/02a60cd7-744d-4573-9466-e094635330e9">

https://paragon-openedx.netlify.app/components/card/#with-loading-state

[Playground demo](https://deploy-preview-2511--paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcIA8BhAhgJygAgJYGcAZCNKXAOwHNsINcZyAXNR3CcgXgB0QALW3AC92zADY8AfF3LZsqTFAB0ASQC2aSjHQAHabNn4MYbn0aNt%2BeAHor23GHwBXVYu39GEfFYDMANgAMVgBM-oE8evqGYACCoowm6Fh46prhMvqiEJQQAMpGJrxmFtZWAG64aK6iaGAw-KKwGIqQqlYAjACs-mn62JnZsfE8iTj9ED3YVlLp8liKAELQAJ7TvbNKABIwpDAYEb2sjKIwJgAquEcwE71OAEaHxyY5jvcXx9eTq-rrijkwYKx2NgHiceH8AWwZCDJPt9FsMDBsAB3RFItBMYEQbBkfDaapLbC3CCMXjYLY7DDYdE4cGAmS3GCMFEMbBqDRaNDaKnkHAAMQgxN22Ba2nYDEY%2BAANNh8FiUdhHPhESNFLDZIsoASPFSwCLRARSSSWIpsLCkFYVbTIV9zSqNSsIj9%2BYLKQJxSxIQUBMImGhxCAvrIkPNHGZ2BJohCgW1zSGw%2BRA3I4x4E5G6dggrHQymbRaFIpnYxdtNbQoJCBJSASTBVDB8AgANogGBQAAailolBAAF1K0jcFASfX4A22iF-N2AL5AA)

```[tasklist]
### Tasks
- [ ] Verify `isLoading` on `Card` is working in consuming MFEs.
- [ ] Understand and fix `isLoading` on Paragon docs site.
```

**Comment by adamstankiewicz** [comment]
> Also I think that it is good idea to implement `isLoading` for Card.Body too.

@PKulkoRaccoonGang What would the `Card` look like with `isLoading` when it used the `Card.Body`, containing a `Card.Header` and `Card.Section`? Given this bug currently, I'm unable to reproduce the expected current state. Is the `Card.Header`'s and `Card.Section`'s `isLoading` support not sufficient?

**Comment by PKulkoRaccoonGang** [comment]
@adamstankiewicz thanks!
I will check after resolved problem with the Skeleton

**Comment by brian-smith-tcril** [comment]
Seems to be working as of https://github.com/openedx/paragon/issues/2420
