### ISSUE TITLE
[alpha] Documentation spacing table styles

### ISSUE THREAD

**Issue by dcoa** [openedx/paragon#2539]
## Bugs

The table that shows the spacing utility classes don't have all the styles, making the information difficult to read.

![image](https://github.com/openedx/paragon/assets/66016493/38a599b7-1c01-4103-a0d4-6263c9927774)

**Expected behavior**

Show the table with the correct spacing and borders.

![image](https://github.com/openedx/paragon/assets/66016493/b761aedb-a35e-45b8-a861-3f974356e06e)

**Comment by khudym** [comment]
PR:https://github.com/openedx/paragon/pull/2677
