### ISSUE TITLE
[CLI improvements] Segment events

### ISSUE THREAD

**Issue by monteri** [openedx/paragon#2543]
[suggestion] To have better observability in how consumers make use of these commands, I might recommend we try dispatching a Segment event describing which command is used and how, similar to how we have `sendTrackInfo` in the component generator tool.

Grooming notes:
* `SEGMENT_KEY` is defined in Netlify. The netlify function will have access to it.

~Speaking of the component generator, we may also want to backlog an issue to migrate its current implementation into this new Paragon CLI as a distinct command (not in scope for this PR).~
(discussed in another issue)

**Comment by PKulkoRaccoonGang** [comment]
Waiting for the main functionality of the Paragon CLI.
