### ISSUE TITLE
[BD-46] Incorrect number of items in DataTable component

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2548]
When selecting elements inside the dropdown of the [DataTable component](https://paragon-openedx.netlify.app/components/datatable/), the number of elements is displayed incorrectly.

![image](https://github.com/openedx/paragon/assets/93188219/a57c053d-e7b1-4220-84a0-800fe8bd96d6)

```[tasklist]
### Tasks
- [ ] Fix the total number of items counter
- [ ] Make sure that all displayed values by the number of elements are displayed correctly
```

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2598
