### ISSUE TITLE
[BD-46] Loading state in DataTable component

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2551]
The [DataTable component](https://paragon-openedx.netlify.app/components/datatable/#loading-state) has to scroll and flicker during the loading state

https://github.com/openedx/paragon/assets/93188219/ef2135e3-4db3-47da-bd85-2189632bf4ac

**Comment by khudym** [comment]
PR:https://github.com/openedx/paragon/pull/2599
