### ISSUE TITLE
[BD-46] Displaying an example of using the DataTable component

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2571]
The [DataTable component](https://paragon-openedx.netlify.app/components/datatable/#maxselectedrows-and-onmaxselectedrows-props) has problems displaying the `maxSelectedRows and onMaxSelectedRows` props example on the documentation site.

![image](https://github.com/openedx/paragon/assets/93188219/38e52aa0-04fb-4b5c-8afb-a511db8a83b7)

```[tasklist]
### Tasks
- [x] Fix code usage example
- [x] Make sure that the problem is only on the documentation site
```

**Comment by viktorrusakov** [comment]
Was fixed in #2598
