### ISSUE TITLE
DataTable filter checkboxes are slightly off center vertically

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2589]
Follow-up from https://github.com/openedx/paragon/pull/2555, it looks like the checkbox label when the badge is included is slightly off center vertically. Is there perhaps an `align-items: center;` that could be added to mitigate?

<img width="311" alt="image" src="https://github.com/openedx/paragon/assets/2828721/cd0e0ded-4f72-40e0-978d-c8fc2570814e">

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2610
