### ISSUE TITLE
[Alpha] styles/css/themes/light/utility-classes.css has `--undefined` variables

### ISSUE THREAD

**Issue by monteri** [openedx/paragon#2614]
1. Some variables have extra space before `!important`(`background-color: var(--pgn-color-action-default-dark-200)  !important;`)
2. Several variables have `var(--undefined)` value (`color: var(--undefined) !important;`)

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2615
