### ISSUE TITLE
[BD-46] Reverse values for the Stack directions

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2627]
Consider adding reverse values for the [Stack Component](https://paragon-openedx.netlify.app/components/stack/) directions. Now we have `"horizontal" | "vertical"` directions, it would be useful to add `"horizontal-reverse" | "vertical-reverse"` directions. This way we will give [Stack Component](https://paragon-openedx.netlify.app/components/stack/) more flexibility (this can be very useful when positioning elements on tablet or mobile screens).

`Vertical` direction
<img width="983" alt="image" src="https://github.com/openedx/paragon/assets/93188219/9490dfdc-1eb9-4731-9a41-630e45aadc55">

`Vertical-reverse` direction
<img width="938" alt="image" src="https://github.com/openedx/paragon/assets/93188219/0accc4fd-f1c9-4dbd-bd53-66d95dced9ed">

**Comment by adamstankiewicz** [comment]
@PKulkoRaccoonGang [curious] Is your proposal to include additional options for the `direction` prop, i.e. `horizontal-reverse` and `vertical-reverse`? I'm wondering whether any other alternative props API ideas are worth considering. For example, perhaps there's still just `horizontal` and `vertical`, but then we could introduce a separate prop for `inverse: true`, or similar. Food for thought; curious to hear your opinion :)

**Comment by PKulkoRaccoonGang** [comment]
@adamstankiewicz Yes, it`s my proposal. I think your idea is the better 🤔 
Let's do it as you suggested, we will leave the horizontal and vertical directions and add a new `reverse` prop. What do you think?

**Comment by adamstankiewicz** [comment]
@PKulkoRaccoonGang Adding a `reverse` prop sounds good to me!

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2678
