### ISSUE TITLE
[BD-46] Visibility of text in an example of using the Layout component

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2637]
It is difficult to recognize the text in the example of using the [Layout component](https://paragon-openedx.netlify.app/components/layout/) on the Paragon documentation site.

Current state:
<img width="1005" alt="image" src="https://github.com/openedx/paragon/assets/93188219/e6235e69-966e-4541-9367-81e16c3697fc">

Proposal:
<img width="977" alt="image" src="https://github.com/openedx/paragon/assets/93188219/29f8908a-d9db-4ee2-a3c6-e71f8fe9260f">

**Comment by adamstankiewicz** [comment]
@PKulkoRaccoonGang Let's just verify the foreground vs. background colors chosen here pass WCAG AA color contrast.

https://webaim.org/resources/contrastchecker/

**Comment by PKulkoRaccoonGang** [comment]
After checking the colors for the example Layout component on the Paragon documentation site. It was discovered that all photon colors (red - `#ff0000`, green - `#008000`, and blue - `#0000ff`) fail accessibility checks for gray - `#454545` text color.

![image](https://github.com/openedx/paragon/assets/93188219/35cb405a-f53c-4e95-bdc8-677a33973456)
![image](https://github.com/openedx/paragon/assets/93188219/9eed3776-fe25-4bac-84c4-7c86d3ada6de)
![image](https://github.com/openedx/paragon/assets/93188219/9bf0860a-6ba0-49e1-89dc-211af5cf9f4f)
