### ISSUE TITLE
`SearchField.SubmitButton` with variant="dark" has no hover styles

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2650]
The `SearchField.SubmitButton` component, when located externally and with `variant="dark"`, does not have proper styles according to the `Button` spec on hover. Interestingly, when `variant="light"`, the `SearchField.SubmitButton` component does have proper hover styles for its color variant.

<img width="753" alt="image" src="https://github.com/openedx/paragon/assets/2828721/fc2adfdc-7904-49af-99f1-eeb17c3cd8c6">

![image](https://github.com/openedx/paragon/assets/2828721/39e9b89b-aa25-4a56-85ab-30a5b51daac4)

[Playground Example](https://paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcIA8BlALgQzAawAQHMMAHAXmAFYBfAPgB0A7XXVGDAJzAAsAxASxgA2UAHQBBKADcM9MDCgMmTCPRQBXAEYBbXmjJSBqmLhLVckegGcIAmMIER8ACgAGF1h064LG7WjRz4XAASYH1DSmcASkoFRW8tHQAhVT9lABkIMAw0XmUSWhAYAA9-NnoMAQLYukZFJCheCTMBDAsLADkMTRh8kCJ8egB9Qbd2LgAzfiFBgHc2YiIYNgKaxTqUdy4%2BQRE0jHVBAHpVteYNsZ4pkQBJeiIU49imJEOGiRPn849toWE1BLQyVSjHiviBaHSmWyuXovWKpXKlRAuCkbF40l0BQEvHwnDQBVwj1qLy%2BWyuYkk0lkUBOLAuPxE4ikMjkT1wyn%2Bvj0FUMxlM5isNjsDhcow8Xh8On8UECITCMAi0TZoKSKQh9AyWRyeQK8KWiKqtQ%2BzDezVaHS6PQK-SGI02nEmO1m8yIi2WIGNn3tDOEewOAiJpzO3vJt3uaEDdVejWNdO%2B5M5quBEoB4MhWphcJK%2BoqBNR6PomJAUHY2AJkZJIZ2FOZ1JqJMwOGoIAANCA0JwYN0LAgANqFKAADWEEDY%2BBAAF02zNeFAOz34L2AOwANgAHBPKEA)

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2675

**Comment by viktorrusakov** [comment]
Related PR from the brand repo: https://github.com/edx/brand-edx.org/pull/77
