### ISSUE TITLE
Update `DataTable`'s filter status bar's messaging

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2676]
# Description

https://paragon-openedx.netlify.app/components/datatable/#frontend-filtering-and-sorting

When a column is filtered, the "Filtered by {accessor}" name is displayed in the `FilterStatus` component. The `accessor` is generally not user-friendly and is often desired to be hidden as a result.

Instead, let's display the `Header` attribute name for the column in the "Filter by {Header}" text instead.

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2757
