### ISSUE TITLE
[BD-46] Going to a non-existent page after clicking on Breadcrumbs links

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2684]
In the [Breadcrumb component](https://paragon-openedx.netlify.app/components/breadcrumb/) on the Paragon documentation site we have the first example ([Basic Usage](https://paragon-openedx.netlify.app/components/breadcrumb/#basic-usage)) in which, after clicking on one of the Breadcrumb links, #link-1 is added to the address bar.
In the second ([Basic Usage (Mobile View)](https://paragon-openedx.netlify.app/components/breadcrumb/#basic-usage-mobile-view)) and third ([Basic Usage (Inverse Palette)](https://paragon-openedx.netlify.app/components/breadcrumb/#basic-usage-inverse-palette)) examples, a transition to a [non-existent page (404) ](https://paragon-openedx.netlify.app/link-3)occurs.

![image](https://github.com/openedx/paragon/assets/93188219/950c4258-4078-4b9a-8972-4fcff1b8801c)

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2760
