### ISSUE TITLE
[alpha] The primary IconButton component does not have a white background

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2688]
In the alpha version of the documentation site, the Paragon, in the example `isActive=true with inverted colors`, IconButton with the `primary` variant does not have a white background color.

https://github.com/openedx/paragon/assets/93188219/de0db615-abb1-4520-9cd3-b4d7948ec47a

**Comment by monteri** [comment]
👍

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2765
