### ISSUE TITLE
`IconButton` instead of custom buttons in the `SearchField`

### ISSUE THREAD

**Issue by monteri** [openedx/paragon#2714]
Instead of custom inner `submit` button and `reset` button we can use `IconButton` that has proper styles. Recently we encountered several issues with custom inner buttons and it will be much consistent for Paragon.

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2719

**Comment by PKulkoRaccoonGang** [comment]
New PR: https://github.com/openedx/paragon/pull/2842
