### ISSUE TITLE
`set-output` (used in "Extract branch name" CI step) is deprecated

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/paragon#2718]
We're currently getting this warning during the "Extract branch name" step of the CI

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more  information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by PKulkoRaccoonGang** [comment]
PR: (DARFT) https://github.com/openedx/paragon/pull/2807
