### ISSUE TITLE
Remove "Technical documentation" from Paragon docs site.

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2775]
The Paragon documentation website includes the label "Technical documentation". However, the Paragon docs site really should be considered as much design documentation as it is technical documentation as well.

<img width="1497" alt="image" src="https://github.com/openedx/paragon/assets/2828721/142a0126-85ca-4e04-9bb0-624e634c1160">

Let's remove the "Technical documentation" label so it doesn't preclude non-technical folks looking at the documentation site.

Let's also move the "Getting Help" ([demo](https://github.com/openedx/paragon#getting-help)) of the README immediately above the "Getting started".

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2814
