### ISSUE TITLE
[Docs site] Keep the menu nav section of currently viewed page expanded

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2776]
As is, when you visit a Paragon docs site page, the associated menu nav section is collapsed:

<img width="1512" alt="image" src="https://github.com/openedx/paragon/assets/2828721/4ca212d2-389c-4390-9174-840f2f9fde03">

To improve docs site usability, we should ensure the containing section of the viewed page stays expanded:

<img width="1509" alt="image" src="https://github.com/openedx/paragon/assets/2828721/452186fd-44e4-46b2-8f39-2281e0b03ec5">

```[tasklist]
### Tasks
- [ ] Ensure the section containing the currently viewed page on the Paragon docs site is persistently expanded such that users know which section they are currently in.
- [ ] Ensure the currently page in the collapsible menu section receives some "active" styling. Perhaps bold font?
```

**Comment by PKulkoRaccoonGang** [comment]
PR (DRAFT):  https://github.com/openedx/paragon/pull/2791
