### ISSUE TITLE
Ensure non-component pages are included in the Algolia DocSearch crawler results

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2780]
Noticed that non-component pages on the Paragon docs site are NOT included in the Algolia results. For example, searching "Color" or "Typography" does not show any results for those standalone pages.

Access thew crawler config here: https://crawler.algolia.com/admin/crawlers/ad38aaca-a9b5-4dce-bc5b-e62391c95fb8/overview

- [ ] Ensure all pages are included in Algolia results.

**Comment by PKulkoRaccoonGang** [comment]
PR: https://github.com/openedx/paragon/pull/2806
