### ISSUE TITLE
[Safari] Not possible to navigate to `Button` using `Tab`

### ISSUE THREAD

**Issue by monteri** [openedx/paragon#2782]
Accessibility problems (it is not possible to navigate through the Button elements of the component using the Tab key, this problem does not exist in the Chrome browser)

**Comment by wittjeff** [comment]
MacOS: https://dequeuniversity.com/mac/keyboard-access-mac#:~:text=Enable%20Safari%20Keyboard%20Accessibility&text=Safari%20Preferences%20%3E%20Advanced%20%3E%20Accessibility%20%3E,each%20item%20on%20a%20webpage.

Firefox should pick up that setting, or use accessibility.tabfocus=7 in config: https://support.mozilla.org/bm/questions/1119986
