### ISSUE TITLE
[Safari] `Textarea` no manual height adjusting

### ISSUE THREAD

**Issue by monteri** [openedx/paragon#2783]
There is no possibility to manually adjust the height of the [Form.Control](https://paragon-openedx.netlify.app/components/form/form-control/#textarea-autoresize) component with the textarea type

Also there is no `min-height` and no `overflow: hidden` for Textarea:

![image](https://github.com/openedx/paragon/assets/36768631/08550d8b-ab7d-4290-8afa-d20b0c8ffe63)

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2818
