### ISSUE TITLE
[Safari] Clicking behavior on `IconButton` is not the same as in Chrome

### ISSUE THREAD

**Issue by monteri** [openedx/paragon#2784]
Clicking behavior on [IconButton](https://paragon-openedx.netlify.app/components/iconbutton/#inverted-colors) with invertColors prop differs from Chrome browser

**Comment by khudym** [comment]
Same situation as [2781](https://github.com/openedx/paragon/issues/2781). Safari does not give focus on the button click
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus
