### ISSUE TITLE
[Playground] Ignored call to 'alert()'. The document is sandboxed, and the 'allow-modals' keyword is not set.

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2794]
## Feedback summary

The current implementation of the Playground, unfortunately, does not call and display native alerts. For example, if we [send an alert call](https://paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYYBOMALgK5knLGmkA8AwhADYcCGADgM4BLAEYcYAOgCCUAG7ciYGFByMmLdlz5DREgCplBAc0MwyKkmqa6IxsRg08BIu6ssZmAIWqVKEEn9YOQTAAaywUGExcfFc3DG4xMkpkAHIACRguCAwAdwgyDigAQhS0AG5Ytwl%2BX14ABTIIXm5DbkpBP3QKizcAX17zOKYAZQALCBz4xMpKpmYAei8fP0HLBYctZz0DY1NVtTZOR20xcQ9oAE99td4cAE0IWgwa6gAzV4xDCBh%2BDFHTGALW6zdZHTY6M6Xa6gzROCHSOQKJSrcrEXpodC9EC9IA) to `onClick`, we get the error:

> Ignored call to 'alert()'. The document is sandboxed, and the 'allow-modals' keyword is not set. 

![image](https://github.com/openedx/paragon/assets/93188219/19e9d9bd-a68b-4756-a561-349c1ce40f0c)

**Comment by brian-smith-tcril** [comment]
I have a PR up that fixes this here https://github.com/openedx/paragon/pull/2987, but I do wonder if we actually want to support using `alert()` in the playground or not.
