### ISSUE TITLE
[paragon-openedx.netlify.app] Form.Checkbox with the disabled prop is available for selection by the cursor

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2797]
## Bug description

[Form.Checkbox](https://paragon-openedx.netlify.app/components/form/form-checkbox/) with the disabled prop is available for selection by the cursor.

https://github.com/openedx/paragon/assets/93188219/d64a5104-57e5-421c-b2dd-0abf8cbca806
```[tasklist]
### Tasks
- [ ] Form.Checkbox with a disabled prop that is not selectable by the cursor
- [ ] Check other components with disabled props for correctness behavior
```

**Comment by khudym** [comment]
PR: https://github.com/openedx/paragon/pull/2888

**Comment by monteri** [comment]
We decided not to do this because in other design systems disabled checkbox, radio and etc. they can be highlighted.
Also answer from ChatGPT on this point:

> Generally, disabling text selection for labels (or any content) on your website is not recommended for several reasons:
> 
> User Experience: Allowing text selection is a standard behavior across most web applications and websites. Disabling it can lead to frustration or confusion for users who might want to copy text for legitimate reasons, such as taking notes, copying configuration details, etc.
> 
> Accessibility: Disabling text selection can negatively impact accessibility. Users who rely on assistive technologies or specific interaction methods may find it more difficult to interact with your content. It's important to ensure that your website is usable and accessible to all users, including those with disabilities.
> 
> Consistency with Web Standards: The web is built on certain foundational principles, including the ability to select and copy text. Deviating from these standards without a compelling reason can harm the overall user experience and accessibility.
