### ISSUE TITLE
[alpha] Missing arrow in Popover component

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2799]
Missing arrow in Popover component (only Brand-Edx.org theme)

![image](https://github.com/openedx/paragon/assets/93188219/f0b2bc4e-7269-4a6f-8477-d30492567022)
```[tasklist]
### Tasks
- [ ] Fix a bug with displaying an arrow in the Popover component
- [ ] Ensure that the arrow is displayed correctly in all variants and themes
```

**Comment by monteri** [comment]
https://github.com/edx/brand-edx.org/pull/79
