### ISSUE TITLE
[alpha] Problem with ProductTour button, after calculations CSS variables

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2800]
In the `ProductTour` component when you click the `Open a product tour` button before performing calculations of CSS variables on the page, the button does not work.

https://github.com/openedx/paragon/assets/93188219/4be3194c-b19c-4461-8ef1-875b5591c705

**Comment by adamstankiewicz** [comment]
Let's sanity check that this issue does NOT happen for consuming MFEs.

**Comment by viktorrusakov** [comment]
The root cause is not CSS variables calculations but incorrect usage of underlying popper element, it is also reproduced in `master` branch as can be seen in the linked PR.

**Comment by monteri** [comment]
https://github.com/openedx/paragon/pull/2863
