### ISSUE TITLE
[paragon-openedx.netlify.app] Large font code examples on the Colors page

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2849]
![Screenshot 2023-11-23 at 16 05 50](https://github.com/openedx/paragon/assets/93188219/c7c738e0-afb2-4f49-8544-e68ce24fb31a)

On the [Colors page](https://paragon-openedx.netlify.app/foundations/colors/#scss-color-usage) we have the font size of the code examples larger than that of the headings. Should the content in the code example have a smaller font size?

For example:
![image](https://github.com/openedx/paragon/assets/93188219/c38e7d69-c20a-4e86-bdc2-ef6e28160867)

```[tasklist]
### Tasks
- [ ] Ensure the text for code examples is the correct size
- [ ] Ensure the code examples on other pages are in the correct font size
```

**Comment by monteri** [comment]
I agree on this, it improves overall experience for the `Colors` page
