### ISSUE TITLE
[alpha] Refactoring the generate-component script

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2851]
After switching to design tokens, in the Paragon repository ([alpha](https://github.com/openedx/paragon/tree/alpha) branch), we stopped using the `_variables.scss` file in Paragon components. Given these changes, we must update the internal `generate-component` script in order to correctly generate the template for new components. This script still creates the `_variables.scss`.

<img width="371" alt="image" src="https://github.com/openedx/paragon/assets/93188219/c76d2846-25e0-4422-9b45-ee94f0005238">

We also need to update the documentation about the component generator on the corresponding page of the Paragon website

![image](https://github.com/openedx/paragon/assets/93188219/7f6a48ad-11d3-456a-82a9-068e2fb07c2e)
![image](https://github.com/openedx/paragon/assets/93188219/015c5d92-9f96-44f7-9540-221e4e668396)

```[tasklist]
### Tasks
- [ ] Ensure that the `_variables.scss` file is not created or imported after executing the generate-component script
- [ ] Ensure that the documentation (on the Paragon website) for the generate-component script is correct
```

**Comment by monteri** [comment]
Since we are not adding many components, will we need a "component generator"? I would consider deprecating the component generator altogether and removing it from the code base. 🤔

**Comment by adamstankiewicz** [comment]
@adamstankiewicz Verify whether the Segment event with this CLI command is used by consumers.

**Comment by viktorrusakov** [comment]
Let's not delete this script, it might be usefull in the future and it does not hurt anybody if it stays in the repository.

@PKulkoRaccoonGang please make these fixes, it will take you at most 10 minutes to do this 🙂

**Comment by PKulkoRaccoonGang** [comment]
Resolved in: https://github.com/openedx/paragon/pull/3076/files
