### ISSUE TITLE
Husky precommit hook doesn't work

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2864]
In the Paragon repository, we have [settings](https://github.com/openedx/paragon/blob/master/package.json#L182) for the [Husky](https://github.com/typicode/husky) pre-commit hook, but it doesn't work.

```[tasklist]
### Tasks
- [ ] Ensure the precommit hook works
```

**Comment by monteri** [comment]
I think it would be valuable to setup it properly
