### ISSUE TITLE
Updating links leading to the React Table library

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#2934]
Now in the [DataTable component](https://paragon-openedx.netlify.app/components/datatable/), we use the 7th version of the [react-table library](https://www.npmjs.com/package/react-table). We have links on the component page that lead to the official website of the library (which is now called `tanstack-table` and has version 8 and an updated API). On the tanstack-table documentation website, there is a mention of outdated [documentation for version 7](https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/api/overview.md) (located in the source code of the GitHub repository). Let's update the library links on Paragon's component page.

**Comment by adamstankiewicz** [comment]
In the short term, we will link to https://github.com/TanStack/table/tree/v7/docs/src/pages/docs for links to `react-table` docs.
