### ISSUE TITLE
Autosuggest in modal overflow problem

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/paragon#2938]
# Minimal repro ([playground](https://paragon-openedx.netlify.app/playroom/?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgNoCWFA8gA4xEA0GFMVr7AXWwYArjwDKVAIZUYyAGZSANjzQBuYqXLU6PJTDCyoXHlXEx9hmFCFZRE6bOQByZ%2Bs0YPAJ14ivJZA9SAB4cINIMYIAhESoqCBIANykveikiKiwCEAhYpXoiGABaFlSAWxSAT2yMBIBhfLAAaywUTFxuXn4iZCovERg0AF8wkgjx7owy6GVwkIB6GLiE0bnIgFkZpQARNKUIAHM10ip6Kn0skAAJGCkoClEWAEJs44xGbtaPtiIht-r9jxWuhsHhTN0FMpVH8xuNRuMEcFNlBlLtlIcAHQ3O4wLzwhHjJFbNH7A4YgAqZ30%2BIJ42RygwAHczgALDAAQViEAoIgOBxgOjeC3pOz2mMp5xgNMR8xFJMx2NgeLeRJRovRZKi0Eq0sJADEIF4yhjOfEeXyBVQhRF5PsZAUDgAZKQAIwslwACl5Dl4pGUyg6MEp0gcRFJ%2Ba9YbTSCk0kVg26lJd5IayhgpFzzfzqJHo%2BMWRYWOsBRRwzBLuZLDRg0RQ2Xc3nSLjvV5ixRS-zyTAAB6ZbIAUS8La4RAgnSr1gwySUAwbjenA1aegMRhhjdICUrK%2BswIXg1BnTMFm3UGQe%2BGb11tOCBqNJszvOzfBYpxWACkpMlxGBUi-gvNb2NU1uUfS1WFfIgrwJG9U3vM1QOocD6BWD1KioFkEn-QC4JAi1EJfZDIOtEJsOArMwIIlYACURDdLDYLIhDnwgqDEVIh88OYwjaiIBp6GaYF9w6ZRcSoZAYAxMA-B8DJyRSfkqAxBT2TiVIXViORnBRaQij3NxhlY6MkISJlWTIMR4jTAF%2BKaYjIgAhiOKfYyiKjQkHLvRjONY-85TFTVtUMjZiX8jEDQgWRlTcxF2UMQiqIgRkgpCPyNQxBpuRgJZ4iSWN0j7EBItOKpsmSiI6nSMALDs3yQrSjKeGylYaqa3LUnyy5SnoCovGqEAytIdkMHU5YiBqxZYhyoL-1iiCEqSlVZTq0kwogCLcSvWq1XlA5pX-fF3F%2BNB0BhEAhiAA))

## Observed

![image](https://github.com/openedx/paragon/assets/112954497/973c63d1-ad51-4431-8bb0-9f84a8030a31)

## Expected

Dropdown goes outside of modal as shown in this issue https://github.com/openedx/modular-learning/issues/117

![image](https://github.com/openedx/paragon/assets/112954497/a7305c87-3d9a-4283-8d1a-3027e3e8cbcf)

**Comment by rpenido** [comment]
Just to give some context, it is not associated with `z-indez`. The problem is that the Dialog and Dialog Body have `d-flex` and are expanding (and adding a scroll), preventing the popup from overflowing correctly.
