### ISSUE TITLE
Test paragon on Python 3.11

### ISSUE THREAD

**Issue by feanil** [openedx/paragon#3018]
This repository is a depedency of edx-platform and needs to be upgraded to Python 3.11 before
the Readwood release is cut (mid-April).

- [ ] Requirements are compiled with Python 3.8
- [ ] Tests are run on Python 3.8 and 3.11
- [ ] (Optional) Tests are also run with 3.12 and passing or 3.12 issues are ticketed.
- [ ] Classifiers in setup.py setup.cfg or pyproject.toml indicate Python 3.11 support
- [ ] A new version is release to PyPI
- [ ] A PR is merged to edx-platform to use the new version

**Comment by mariajgrimaldi** [comment]
There is no python in this repo so we don't have to do anything for this upgrade.
