### ISSUE TITLE
Update local frontend-platform documentation

### ISSUE THREAD

**Issue by chris1tapia** [openedx/paragon#3063]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/edx-platform/issues/34765
- [ ] https://github.com/openedx/edx-platform/issues/34766
```

**Comment by dcoa** [comment]
I reviewed the documentation here https://github.com/openedx/frontend-platform/pull/689/files#diff-0e764ad3abf238c70590cbada2902ec481874e525cd7cd80da1a5875afda7d9a and made some improvements. Also, I checked the JSDoc to reflect the hook behavior, and with that, the gh-pages stay updated once the PR is merged. Finally, I made a small recommendation for the migrating document https://openedx.atlassian.net/wiki/spaces/BPL/pages/3770744958/Migrating+MFEs+to+Paragon+design+tokens+and+CSS+variables
