### ISSUE TITLE
[bug]: ModalPopup doesn't close on button click on mobile devices

### ISSUE THREAD

**Issue by ihor-romaniuk** [openedx/paragon#3081]
Components: [ModalPopup](https://paragon-openedx.netlify.app/components/modal/modal-popup)

## Feedback summary

When you try to close an open ModalPopup modal for mobile devices, the closing does not occur, but 2 events are executed: close event and open event. Which makes it impossible to close the modal by clicking on the call button.
Note: this error does not occur for the desktop version.

https://github.com/openedx/paragon/assets/17108583/4c793cf1-efeb-41b1-b34e-c5fcba8999e9

## Improvements

The modal should both open and close by clicking on the call button for desktop and mobile devices.

**Comment by brian-smith-tcril** [comment]
This seems to be an issue with how we're using `react-focus-on`, and is something others have run into as well https://github.com/theKashey/react-focus-on/issues/33.

The [`react-focus-on` readme](https://github.com/theKashey/react-focus-on?tab=readme-ov-file#api) has

> `[onClickOutside]` - on click outside of "focus" area. (actually on any event "outside")

In our use case, this means `onClickOutside` is calling `onClose` when it receives a `touchstart` event, but the button doesn't do anything until it recieves a react `click` event, which happens afterwards during the same press.
