### ISSUE TITLE
Make `isOverflowVisible` on `ModalDialog` a required prop without a default value?

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/paragon#3116]
As of https://github.com/openedx/paragon/pull/2939, `isOverflowVisible` on `ModalDialog` defaults to `true`. This can lead to issues such as https://github.com/openedx/frontend-app-course-authoring/issues/986.

If, however, `isOverflowVisible` is `false` - we encounter the original problem seen in https://github.com/openedx/paragon/issues/2938.

With the current implementation either value being set as the default will lead to some consumers encountering unintended behavior, so I'd like to propose we don't set a default and instead require consumers decide if they want overflow or not.

It's also possible there's a more robust solution I haven't thought of yet, and this may tie in to https://github.com/openedx/paragon/issues/2990 somehow.

**Comment by PKulkoRaccoonGang** [comment]
https://github.com/openedx/paragon/pull/3279

**Comment by PKulkoRaccoonGang** [comment]
Hi @brian-smith-tcril, should we close this issue?

**Comment by brian-smith-tcril** [comment]
Great catch @PKulkoRaccoonGang!
