### ISSUE TITLE
Landing Design Tokens

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/paragon#3273]
```[tasklist]
### Need to land before we can cut 23
- [ ] https://github.com/openedx/paragon/pull/3186
- [ ] https://github.com/openedx/paragon/pull/3153
```

```[tasklist]
### Would be nice to do before we cut 23
- [ ] https://github.com/openedx/paragon/issues/3116
```

```[tasklist]
### Branches/Deployments/Publishing
- [x] Create `release-23.x`, `release-22.x` branches (sync)
- [ ] https://github.com/openedx/paragon/issues/3272
- [x] Create `next` branch (sync)
- [x] Set default branch on GH to `release-23.x` (sync)
- [ ] https://github.com/openedx/paragon/pull/3333
- [ ] https://github.com/openedx/paragon/issues/3271
- [ ] https://github.com/openedx/paragon/pull/3158
```

**Comment by PKulkoRaccoonGang** [comment]
Sync master to alpha -  https://github.com/openedx/paragon/pull/3303

**Comment by PKulkoRaccoonGang** [comment]
[inform]:
> we don’t want to release off master anymore; instead, we only want to release off specific named release branches (release-23.x)

According to [the discussions on PWG](https://openedx.atlassian.net/wiki/spaces/BPL/pages/4632641538/2024-11-20+Meeting+notes) we decided to have several branches, so this PR for inclusion in `master` has lost its relevance.
The alpha branch will be used for further preparation for the release.
https://github.com/openedx/paragon/pull/3303

**Comment by PKulkoRaccoonGang** [comment]
Update readme to explain where to point breaking change PRs (async):
https://github.com/openedx/paragon/pull/3333
