### ISSUE TITLE
Reviewing dependencies for @edx/stylelint-config-edx/@edx/eslint-config configs

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/paragon#3294]
Since we use [@edx/stylelint-config-edx](https://github.com/openedx/stylelint-config-edx) as a base for [the stylelint configuration](https://github.com/openedx/paragon/blob/master/.stylelintrc.json#L2), do we need to have [stylelint-config-standard-scss](https://github.com/openedx/paragon/blob/master/package.json#L143) as a dependency?

It might also be a good idea to check if all related packages are up to date for [@edx/eslint-config](https://github.com/openedx/eslint-config)

**Comment by brian-smith-tcril** [comment]
* Just using [@edx/stylelint-config-edx](https://github.com/openedx/stylelint-config-edx) seems better
  * Context: Was used as a base for `stylelintrc` before moving to use the `@edx` package
* Updating to latest [@edx/eslint-config](https://github.com/openedx/eslint-config) also seems like a generally good idea

**Comment by PKulkoRaccoonGang** [comment]
Thanks for merging this PR. Closed.
