### ISSUE TITLE
Need some new Icons 

### ISSUE THREAD

**Issue by awaisdar001** [openedx/paragon#766]
We need following Icons for our work in discussions MFE
1. "Star" solid & regular icons
2. Flag Icon solid
3. Icon solid
4. Thumbtack

Can this be provided as a part of paragon so we do not need to depend upon FA anymore?
thanks.
<img width="241" alt="Screen Shot 2021-06-29 at 1 47 53 PM" src="https://user-images.githubusercontent.com/4252738/123767167-b839c600-d8e0-11eb-94a7-d16be6b27e2b.png">

<img width="229" alt="Screen Shot 2021-06-29 at 4 02 21 PM" src="https://user-images.githubusercontent.com/4252738/123786769-81b97680-d8f3-11eb-9614-4d67ac1625a0.png">

FYI -- @abutterworth

**Comment by abutterworth** [comment]
Yes let’s add those. Who is the designer who worked on the design? Here is an outline of the designer’s responsibilities when adding an icon to Paragon https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=14403%3A53 

For engineering, directions for adding a component to Paragon is here: https://github.com/edx/paragon/tree/master/icons

**Comment by adamstankiewicz** [comment]
@awaisdar001 Are these icons still necessary? It looks like https://paragon-openedx.netlify.app/foundations/icons has the star and flag icons as requested. Is the thumbtack still necessary? If so, may you work with a designer to get it added to the Figma library and this repo by following the above instructions? :) Thanks!
