### ISSUE TITLE
New component generator

### ISSUE THREAD

**Issue by arizzitano** [openedx/paragon#80]
Idea: an npm script to generate a directory, starter files, and a webpack entry point for a new component, given its name. This script would be targeted towards Paragon newcomers who may not be familiar with code conventions (or React!!) and just need an easy way to get started. But, it'd make things quicker for longtime contributors as well. So you'd run something like
```
$ npm run create-component Breadcrumb
```

And then you'd end up with a new directory within `/src`:
```
└─┬ Breadcrumb
  ├── Breadcrumb.scss
  ├── Breadcrumb.test.jsx
  ├── Breadcrumb.stories.jsx
  ├── index.jsx
  └── README.md
```

Each file would contain a minimal amount of boilerplate (imports, `storiesOf`, a starter README, etc.). I'm leaning towards *not* including boilerplate for the actual component itself within `index.jsx`, since it could differ significantly between stateless/stateful. I dunno though what do you guys think??

There's probably a package out there that does this. It used to be Yeoman's jam but I think that's fallen out of style/is unmaintained. Maybe we could use something like https://www.npmjs.com/package/create-component-app?? That might be too heavyweight for our purposes though.

**Comment by adamstankiewicz** [comment]
This is complete. See README for instructions: https://github.com/openedx/paragon#2-create-new-component
